import type {
  PersistedAppStateContract,
  PersistedSpaceArchiveNodeSnapshot,
  PersistedSpaceArchiveRecord,
  PersistedSpaceArchiveSpaceSnapshot,
} from '@shared/contracts/persistedAppState'
import type {
  NormalizedPersistedAppStateContract,
  NormalizedPersistedNodeContract,
  NormalizedPersistedSpaceArchiveNodeSnapshot,
  NormalizedPersistedSpaceArchiveRecord,
  NormalizedPersistedSpaceArchiveSpaceSnapshot,
  NormalizedPersistedSpaceContract,
  NormalizedPersistedWorkspaceContract,
} from '@shared/contracts/normalizedPersistedAppState'
import { isPersistedAppState } from './persistedAppStateValidation'

export type PersistedSettingsNormalizer<TSettings extends object> = (
  value: unknown,
) => TSettings | null

function isSettingsRecord(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === 'object' && !Array.isArray(value)
}

function normalizeNodeForMerge(
  node: PersistedAppStateContract<Record<string, unknown>>['workspaces'][number]['nodes'][number],
): NormalizedPersistedNodeContract {
  return {
    ...node,
    status: node.status ?? null,
    startedAt: node.startedAt ?? null,
    endedAt: node.endedAt ?? null,
    exitCode: node.exitCode ?? null,
    lastError: node.lastError ?? null,
    scrollback: node.scrollback ?? null,
    agent: node.agent ?? null,
    task: node.task ?? null,
  }
}

function normalizeSpaceForMerge(
  space: NonNullable<
    PersistedAppStateContract<Record<string, unknown>>['workspaces'][number]['spaces']
  >[number],
  workspacePath: string,
  index: number,
  validNodeIds: ReadonlySet<string>,
): NormalizedPersistedSpaceContract {
  return {
    ...space,
    directoryPath: space.directoryPath ?? workspacePath,
    targetMountId: space.targetMountId ?? null,
    parentSpaceId: space.parentSpaceId ?? null,
    boundary: space.boundary ?? null,
    sortOrder: space.sortOrder ?? index,
    pinned: space.pinned ?? false,
    labelColor: space.labelColor ?? null,
    nodeIds: (space.nodeIds ?? []).filter(nodeId => validNodeIds.has(nodeId)),
    rect: space.rect ?? null,
  }
}

function normalizeArchiveSpaceForMerge(
  space: PersistedSpaceArchiveSpaceSnapshot,
  workspacePath: string,
): NormalizedPersistedSpaceArchiveSpaceSnapshot {
  return {
    ...space,
    directoryPath: space.directoryPath ?? workspacePath,
    targetMountId: space.targetMountId ?? null,
    parentSpaceId: space.parentSpaceId ?? null,
    boundary: space.boundary?.allowedMountIds.length ? space.boundary : null,
    labelColor: space.labelColor ?? null,
    nodeIds: space.nodeIds ?? [],
    rect: space.rect ?? null,
  }
}

function normalizeArchiveNodeForMerge(
  node: PersistedSpaceArchiveNodeSnapshot,
): NormalizedPersistedSpaceArchiveNodeSnapshot {
  const base = {
    id: node.id,
    title: node.title ?? '',
    frame: node.frame ?? null,
    labelColorOverride: node.labelColorOverride ?? null,
  }
  switch (node.kind) {
    case 'terminal':
      return {
        ...node,
        ...base,
        runtimeKind: node.runtimeKind ?? null,
        executionDirectory: node.executionDirectory ?? null,
        expectedDirectory: node.expectedDirectory ?? null,
        startedAt: node.startedAt ?? null,
        endedAt: node.endedAt ?? null,
        exitCode: node.exitCode ?? null,
        lastError: node.lastError ?? null,
      }
    case 'agent':
      return {
        ...node,
        ...base,
        status: node.status ?? null,
        provider: node.provider ?? null,
        prompt: node.prompt ?? '',
        model: node.model ?? null,
        effectiveModel: node.effectiveModel ?? null,
        launchMode: node.launchMode ?? 'new',
        resumeSessionId: node.resumeSessionId ?? null,
        executionDirectory: node.executionDirectory ?? null,
        expectedDirectory: node.expectedDirectory ?? null,
        directoryMode: node.directoryMode ?? 'workspace',
        customDirectory: node.customDirectory ?? null,
        shouldCreateDirectory: node.shouldCreateDirectory ?? false,
        taskId: node.taskId ?? null,
        startedAt: node.startedAt ?? null,
        endedAt: node.endedAt ?? null,
        exitCode: node.exitCode ?? null,
        lastError: node.lastError ?? null,
      }
    case 'task':
      return {
        ...node,
        ...base,
        status: node.status ?? 'todo',
        priority: node.priority ?? 'medium',
        tags: node.tags ?? [],
        linkedAgentNodeId: node.linkedAgentNodeId ?? null,
        lastRunAt: node.lastRunAt ?? null,
        autoGeneratedTitle: node.autoGeneratedTitle ?? false,
        createdAt: node.createdAt ?? null,
        updatedAt: node.updatedAt ?? null,
      }
    case 'note':
      return { ...node, ...base }
  }
}

function normalizeArchiveForMerge(
  archive: PersistedSpaceArchiveRecord,
  workspacePath: string,
): NormalizedPersistedSpaceArchiveRecord {
  const spaces = (archive.spaces ?? []).map(space =>
    normalizeArchiveSpaceForMerge(space, workspacePath),
  )
  const pullRequest = archive.git?.pullRequest
  const { git: _git, nodes: _nodes, space: _space, spaces: _spaces, ...identity } = archive
  return {
    ...identity,
    git: archive.git
      ? {
          worktreePath: archive.git.worktreePath ?? null,
          branch: archive.git.branch ?? null,
          head: archive.git.head ?? null,
          pullRequest: pullRequest
            ? {
                ref: {
                  providerId: 'github',
                  kind: 'pull_request',
                  id: pullRequest.ref.id,
                  url: pullRequest.ref.url ?? null,
                },
                number: pullRequest.number,
                title: pullRequest.title,
                state: pullRequest.state,
                isDraft: pullRequest.isDraft ?? false,
                authorLogin: pullRequest.authorLogin ?? null,
                updatedAt: pullRequest.updatedAt ?? null,
                baseRefName: pullRequest.baseRefName ?? null,
                headRefName: pullRequest.headRefName ?? null,
              }
            : null,
        }
      : null,
    space: {
      id: archive.space.id,
      name: archive.space.name,
      directoryPath: archive.space.directoryPath ?? workspacePath,
      labelColor: archive.space.labelColor ?? null,
      rect: archive.space.rect ?? null,
    },
    ...(spaces.length > 0 ? { spaces } : {}),
    nodes: (archive.nodes ?? []).map(normalizeArchiveNodeForMerge),
  }
}

function normalizeWorkspaceForMerge(
  workspace: PersistedAppStateContract<Record<string, unknown>>['workspaces'][number],
): NormalizedPersistedWorkspaceContract {
  const validNodeIds = new Set(workspace.nodes.map(node => node.id))
  const spaces = (workspace.spaces ?? []).map((space, index) =>
    normalizeSpaceForMerge(space, workspace.path, index, validNodeIds),
  )
  const activeSpaceId =
    workspace.activeSpaceId &&
    spaces.some(space => space.id === workspace.activeSpaceId && !space.parentSpaceId)
      ? workspace.activeSpaceId
      : null

  return {
    ...workspace,
    worktreesRoot: workspace.worktreesRoot ?? '',
    nodes: workspace.nodes.map(normalizeNodeForMerge),
    viewport: workspace.viewport ?? { x: 0, y: 0, zoom: 1 },
    isMinimapVisible: workspace.isMinimapVisible ?? true,
    spaces,
    activeSpaceId,
    spaceArchiveRecords: (workspace.spaceArchiveRecords ?? []).map(archive =>
      normalizeArchiveForMerge(archive, workspace.path),
    ),
  }
}

export function normalizePersistedAppStateForMerge<TSettings extends object>(
  value: unknown,
  normalizeSettings: PersistedSettingsNormalizer<TSettings>,
): NormalizedPersistedAppStateContract<TSettings> | null {
  if (!isPersistedAppState(value, isSettingsRecord)) {
    return null
  }
  const settings = normalizeSettings(value.settings)
  if (!settings) {
    return null
  }
  const workspaces = value.workspaces.map(normalizeWorkspaceForMerge)
  return {
    ...value,
    activeWorkspaceId:
      value.activeWorkspaceId &&
      workspaces.some(workspace => workspace.id === value.activeWorkspaceId)
        ? value.activeWorkspaceId
        : null,
    workspaces,
    settings,
  }
}
