import type {
  PersistedAgentNodeData,
  PersistedDocumentNodeData,
  PersistedImageNodeData,
  PersistedNodeContract,
  PersistedNoteNodeData,
  PersistedRoleNodeData,
  PersistedRoleRunRecord,
  PersistedTaskAgentSessionRecord,
  PersistedTaskNodeData,
  PersistedTerminalAgentSessionBinding,
  PersistedWebsiteNodeData,
  PersistedWorkspaceNodeKind,
} from '@shared/contracts/persistedAppState'
import {
  isAgentProvider,
  isAgentRuntimeStatus,
  isCanvasImageMimeType,
  isExecutionDirectoryMode,
  isFiniteNumber,
  isLaunchMode,
  isNodeFrameOrNull,
  isNodeLabelColorOverride,
  isNullableAgentProvider,
  isNullableAgentRuntimeStatus,
  isNullableFiniteNumber,
  isNullableString,
  isOptionalNullableString,
  isPoint,
  isRecord,
  isStringArray,
  isTaskPriority,
  isTaskRuntimeStatus,
  isTerminalGeometry,
  isTerminalRuntimeKind,
  isWorkspaceNodeKind,
} from './persistedStateValidationPrimitives'

function isOptionalBoolean(value: unknown): boolean {
  return value === undefined || typeof value === 'boolean'
}

function isTerminalAgentSessionBinding(
  value: unknown,
): value is PersistedTerminalAgentSessionBinding {
  return (
    isRecord(value) &&
    isAgentProvider(value.provider) &&
    isNullableString(value.resumeSessionId) &&
    isOptionalBoolean(value.resumeSessionIdVerified)
  )
}

function isTaskAgentSessionRecord(value: unknown): value is PersistedTaskAgentSessionRecord {
  return (
    isRecord(value) &&
    typeof value.id === 'string' &&
    isAgentProvider(value.provider) &&
    isNullableString(value.resumeSessionId) &&
    isOptionalBoolean(value.resumeSessionIdVerified) &&
    typeof value.prompt === 'string' &&
    isNullableString(value.model) &&
    isNullableString(value.effectiveModel) &&
    typeof value.boundDirectory === 'string' &&
    typeof value.lastDirectory === 'string' &&
    typeof value.createdAt === 'string' &&
    typeof value.lastRunAt === 'string' &&
    isNullableString(value.endedAt) &&
    isNullableFiniteNumber(value.exitCode) &&
    isAgentRuntimeStatus(value.status)
  )
}

function isAgentNodeData(value: unknown): value is PersistedAgentNodeData {
  return (
    isRecord(value) &&
    isAgentProvider(value.provider) &&
    (value.prompt === undefined || typeof value.prompt === 'string') &&
    (value.model === undefined || isNullableString(value.model)) &&
    (value.effectiveModel === undefined || isNullableString(value.effectiveModel)) &&
    (value.launchMode === undefined || isLaunchMode(value.launchMode)) &&
    (value.resumeSessionId === undefined || isNullableString(value.resumeSessionId)) &&
    isOptionalBoolean(value.resumeSessionIdVerified) &&
    typeof value.executionDirectory === 'string' &&
    (value.expectedDirectory === undefined || isNullableString(value.expectedDirectory)) &&
    (value.directoryMode === undefined || isExecutionDirectoryMode(value.directoryMode)) &&
    (value.customDirectory === undefined || isNullableString(value.customDirectory)) &&
    isOptionalBoolean(value.shouldCreateDirectory) &&
    (value.taskId === undefined || isNullableString(value.taskId))
  )
}

function isTaskNodeData(value: unknown): value is PersistedTaskNodeData {
  return (
    isRecord(value) &&
    typeof value.requirement === 'string' &&
    (value.status === undefined || isTaskRuntimeStatus(value.status)) &&
    (value.priority === undefined || isTaskPriority(value.priority)) &&
    (value.tags === undefined || isStringArray(value.tags)) &&
    (value.linkedAgentNodeId === undefined || isNullableString(value.linkedAgentNodeId)) &&
    (value.agentSessions === undefined ||
      (Array.isArray(value.agentSessions) &&
        value.agentSessions.every(isTaskAgentSessionRecord))) &&
    (value.lastRunAt === undefined || isNullableString(value.lastRunAt)) &&
    (value.autoGeneratedTitle === undefined || typeof value.autoGeneratedTitle === 'boolean') &&
    (value.createdAt === undefined || isNullableString(value.createdAt)) &&
    (value.updatedAt === undefined || isNullableString(value.updatedAt))
  )
}

function isNoteNodeData(value: unknown): value is PersistedNoteNodeData {
  return isRecord(value) && typeof value.text === 'string'
}

function isRoleRunRecord(value: unknown): value is PersistedRoleRunRecord {
  return (
    isRecord(value) &&
    typeof value.id === 'string' &&
    typeof value.input === 'string' &&
    typeof value.prompt === 'string' &&
    typeof value.outputFormat === 'string' &&
    isNullableAgentProvider(value.provider) &&
    isNullableString(value.agentNodeId) &&
    isNullableString(value.sessionId) &&
    typeof value.createdAt === 'string'
  )
}

function isRoleNodeData(value: unknown): value is PersistedRoleNodeData {
  return (
    isRecord(value) &&
    typeof value.roleId === 'string' &&
    typeof value.roleName === 'string' &&
    typeof value.roleDescription === 'string' &&
    typeof value.promptTemplate === 'string' &&
    typeof value.inputHint === 'string' &&
    typeof value.outputFormat === 'string' &&
    typeof value.input === 'string' &&
    isNullableAgentProvider(value.selectedProvider) &&
    isNullableString(value.linkedAgentNodeId) &&
    Array.isArray(value.runHistory) &&
    value.runHistory.every(isRoleRunRecord) &&
    isNullableString(value.createdAt) &&
    isNullableString(value.updatedAt)
  )
}

function isImageNodeData(value: unknown): value is PersistedImageNodeData {
  return (
    isRecord(value) &&
    typeof value.assetId === 'string' &&
    isCanvasImageMimeType(value.mimeType) &&
    isNullableString(value.fileName) &&
    (value.naturalWidth === null ||
      (isFiniteNumber(value.naturalWidth) && value.naturalWidth > 0)) &&
    (value.naturalHeight === null ||
      (isFiniteNumber(value.naturalHeight) && value.naturalHeight > 0))
  )
}

function isDocumentNodeData(value: unknown): value is PersistedDocumentNodeData {
  return isRecord(value) && typeof value.uri === 'string' && value.uri.trim().length > 0
}

function isWebsiteNodeData(value: unknown): value is PersistedWebsiteNodeData {
  return (
    isRecord(value) &&
    typeof value.url === 'string' &&
    typeof value.pinned === 'boolean' &&
    (value.sessionMode === 'shared' ||
      value.sessionMode === 'incognito' ||
      value.sessionMode === 'profile') &&
    isNullableString(value.profileId) &&
    (value.sessionMode !== 'profile' || value.profileId !== null) &&
    (value.browserMode === undefined ||
      value.browserMode === 'native' ||
      value.browserMode === 'iframe') &&
    isOptionalBoolean(value.isFullscreen) &&
    (value.previousFrame === undefined || isNodeFrameOrNull(value.previousFrame))
  )
}

function isAgentPayloadForKind(kind: PersistedWorkspaceNodeKind, value: unknown): boolean {
  if (kind === 'terminal') {
    return value === null || isTerminalAgentSessionBinding(value)
  }
  if (kind === 'agent') {
    return value === null || isAgentNodeData(value)
  }
  return value === null
}

function isNodePayloadForKind(kind: PersistedWorkspaceNodeKind, value: unknown): boolean {
  switch (kind) {
    case 'task':
      return value === null || isTaskNodeData(value)
    case 'note':
      return value === null || isNoteNodeData(value)
    case 'role':
      return value === null || isRoleNodeData(value)
    case 'image':
      return value === null || isImageNodeData(value)
    case 'document':
      return value === null || isDocumentNodeData(value)
    case 'website':
      return value === null || isWebsiteNodeData(value)
    default:
      return value === null
  }
}

function isNodeWorkerBinding(value: unknown): boolean {
  return (
    value === undefined ||
    value === null ||
    (isRecord(value) &&
      typeof value.endpointId === 'string' &&
      value.endpointId.trim().length > 0 &&
      isNullableString(value.mountId))
  )
}

export function isPersistedNode(value: unknown): value is PersistedNodeContract {
  if (!isRecord(value) || !isWorkspaceNodeKind(value.kind)) {
    return false
  }

  return (
    typeof value.id === 'string' &&
    value.id.trim().length > 0 &&
    isOptionalNullableString(value.sessionId) &&
    typeof value.title === 'string' &&
    isOptionalBoolean(value.titlePinnedByUser) &&
    isPoint(value.position) &&
    isFiniteNumber(value.width) &&
    isFiniteNumber(value.height) &&
    isOptionalNullableString(value.profileId) &&
    (value.runtimeKind === undefined ||
      value.runtimeKind === null ||
      isTerminalRuntimeKind(value.runtimeKind)) &&
    (value.terminalGeometry === undefined ||
      value.terminalGeometry === null ||
      isTerminalGeometry(value.terminalGeometry)) &&
    isNodeWorkerBinding(value.workerBinding) &&
    (value.terminalProviderHint === undefined ||
      value.terminalProviderHint === null ||
      isAgentProvider(value.terminalProviderHint)) &&
    (value.terminalAgentBinding === undefined ||
      value.terminalAgentBinding === null ||
      isTerminalAgentSessionBinding(value.terminalAgentBinding)) &&
    (value.labelColorOverride === undefined ||
      isNodeLabelColorOverride(value.labelColorOverride)) &&
    (value.sidebarSortOrder === undefined ||
      value.sidebarSortOrder === null ||
      isFiniteNumber(value.sidebarSortOrder)) &&
    isNullableAgentRuntimeStatus(value.status) &&
    isNullableString(value.startedAt) &&
    isNullableString(value.endedAt) &&
    isNullableFiniteNumber(value.exitCode) &&
    isNullableString(value.lastError) &&
    isNullableString(value.scrollback) &&
    isOptionalNullableString(value.executionDirectory) &&
    isOptionalNullableString(value.expectedDirectory) &&
    isAgentPayloadForKind(value.kind, value.agent) &&
    isNodePayloadForKind(value.kind, value.task)
  )
}
