import type {
  PersistedSpaceArchiveGitSnapshot,
  PersistedSpaceArchiveNodeSnapshot,
  PersistedSpaceArchiveRecord,
  PersistedSpaceArchiveSpaceSnapshot,
} from '@shared/contracts/persistedAppState'
import { isLabelColor } from '@shared/types/labelColor'
import {
  isNodeFrameOrNull,
  isNodeLabelColorOverride,
  isNullableAgentProvider,
  isNullableAgentRuntimeStatus,
  isNullableExecutionDirectoryMode,
  isNullableFiniteNumber,
  isNullableLaunchMode,
  isOptionalNullableString,
  isNullableTerminalRuntimeKind,
  isRecord,
  isRectOrNull,
  isSpaceBoundary,
  isStringArray,
  isTaskPriority,
  isTaskRuntimeStatus,
} from './persistedStateValidationPrimitives'

function isOptionalBoolean(value: unknown): boolean {
  return value === undefined || typeof value === 'boolean'
}

function isPullRequestSummary(value: unknown): boolean {
  if (!isRecord(value) || !isRecord(value.ref)) {
    return false
  }
  return (
    value.ref.providerId === 'github' &&
    value.ref.kind === 'pull_request' &&
    typeof value.ref.id === 'string' &&
    value.ref.id.trim().length > 0 &&
    isOptionalNullableString(value.ref.url) &&
    Number.isSafeInteger(value.number) &&
    (value.number as number) > 0 &&
    typeof value.title === 'string' &&
    (value.state === 'open' || value.state === 'closed' || value.state === 'merged') &&
    isOptionalBoolean(value.isDraft) &&
    isOptionalNullableString(value.authorLogin) &&
    isOptionalNullableString(value.updatedAt) &&
    isOptionalNullableString(value.baseRefName) &&
    isOptionalNullableString(value.headRefName)
  )
}

function isArchiveGitSnapshot(value: unknown): value is PersistedSpaceArchiveGitSnapshot {
  return (
    isRecord(value) &&
    isOptionalNullableString(value.worktreePath) &&
    isOptionalNullableString(value.branch) &&
    isOptionalNullableString(value.head) &&
    (value.pullRequest === undefined ||
      value.pullRequest === null ||
      isPullRequestSummary(value.pullRequest))
  )
}

function hasArchiveNodeBase(value: Record<string, unknown>): boolean {
  return (
    typeof value.id === 'string' &&
    value.id.trim().length > 0 &&
    (value.title === undefined || typeof value.title === 'string') &&
    (value.frame === undefined || isNodeFrameOrNull(value.frame)) &&
    (value.labelColorOverride === undefined || isNodeLabelColorOverride(value.labelColorOverride))
  )
}

function isArchiveNodeSnapshot(value: unknown): value is PersistedSpaceArchiveNodeSnapshot {
  if (!isRecord(value) || !hasArchiveNodeBase(value)) {
    return false
  }

  switch (value.kind) {
    case 'terminal':
      return (
        (value.runtimeKind === undefined || isNullableTerminalRuntimeKind(value.runtimeKind)) &&
        isOptionalNullableString(value.executionDirectory) &&
        isOptionalNullableString(value.expectedDirectory) &&
        isOptionalNullableString(value.startedAt) &&
        isOptionalNullableString(value.endedAt) &&
        (value.exitCode === undefined || isNullableFiniteNumber(value.exitCode)) &&
        isOptionalNullableString(value.lastError)
      )
    case 'agent':
      return (
        (value.status === undefined || isNullableAgentRuntimeStatus(value.status)) &&
        (value.provider === undefined || isNullableAgentProvider(value.provider)) &&
        (value.prompt === undefined || typeof value.prompt === 'string') &&
        isOptionalNullableString(value.model) &&
        isOptionalNullableString(value.effectiveModel) &&
        (value.launchMode === undefined || isNullableLaunchMode(value.launchMode)) &&
        isOptionalNullableString(value.resumeSessionId) &&
        isOptionalBoolean(value.resumeSessionIdVerified) &&
        isOptionalNullableString(value.executionDirectory) &&
        isOptionalNullableString(value.expectedDirectory) &&
        (value.directoryMode === undefined ||
          isNullableExecutionDirectoryMode(value.directoryMode)) &&
        isOptionalNullableString(value.customDirectory) &&
        isOptionalBoolean(value.shouldCreateDirectory) &&
        isOptionalNullableString(value.taskId) &&
        isOptionalNullableString(value.startedAt) &&
        isOptionalNullableString(value.endedAt) &&
        (value.exitCode === undefined || isNullableFiniteNumber(value.exitCode)) &&
        isOptionalNullableString(value.lastError)
      )
    case 'task':
      return (
        typeof value.requirement === 'string' &&
        (value.status === undefined || isTaskRuntimeStatus(value.status)) &&
        (value.priority === undefined || isTaskPriority(value.priority)) &&
        (value.tags === undefined || isStringArray(value.tags)) &&
        isOptionalNullableString(value.linkedAgentNodeId) &&
        isOptionalNullableString(value.lastRunAt) &&
        isOptionalBoolean(value.autoGeneratedTitle) &&
        isOptionalNullableString(value.createdAt) &&
        isOptionalNullableString(value.updatedAt)
      )
    case 'note':
      return typeof value.text === 'string'
    default:
      return false
  }
}

function isArchiveSpaceSnapshot(value: unknown): value is PersistedSpaceArchiveSpaceSnapshot {
  return (
    isRecord(value) &&
    typeof value.id === 'string' &&
    value.id.trim().length > 0 &&
    typeof value.name === 'string' &&
    (value.directoryPath === undefined || typeof value.directoryPath === 'string') &&
    isOptionalNullableString(value.targetMountId) &&
    isOptionalNullableString(value.parentSpaceId) &&
    (value.boundary === undefined || value.boundary === null || isSpaceBoundary(value.boundary)) &&
    (value.labelColor === undefined ||
      value.labelColor === null ||
      isLabelColor(value.labelColor)) &&
    (value.nodeIds === undefined || isStringArray(value.nodeIds)) &&
    (value.rect === undefined || isRectOrNull(value.rect))
  )
}

export function isPersistedSpaceArchiveRecord(
  value: unknown,
): value is PersistedSpaceArchiveRecord {
  if (!isRecord(value) || !isRecord(value.space)) {
    return false
  }

  return (
    typeof value.id === 'string' &&
    value.id.trim().length > 0 &&
    typeof value.archivedAt === 'string' &&
    value.archivedAt.trim().length > 0 &&
    (value.git === undefined || value.git === null || isArchiveGitSnapshot(value.git)) &&
    typeof value.space.id === 'string' &&
    value.space.id.trim().length > 0 &&
    typeof value.space.name === 'string' &&
    (value.space.directoryPath === undefined || typeof value.space.directoryPath === 'string') &&
    (value.space.labelColor === undefined ||
      value.space.labelColor === null ||
      isLabelColor(value.space.labelColor)) &&
    (value.space.rect === undefined || isRectOrNull(value.space.rect)) &&
    (value.spaces === undefined ||
      (Array.isArray(value.spaces) && value.spaces.every(isArchiveSpaceSnapshot))) &&
    (value.nodes === undefined ||
      (Array.isArray(value.nodes) && value.nodes.every(isArchiveNodeSnapshot)))
  )
}
