import type {
  PersistedSpaceArchiveGitSnapshot,
  PersistedSpaceArchiveNodeSnapshot,
  PersistedSpaceArchiveRecord,
  PersistedSpaceArchiveSpaceSnapshot,
} from '@shared/contracts/persistedAppState'
import { isLabelColor } from '@shared/types/labelColor'
import {
  isNodeFrameOrNull,
  isNodeLabelColorOverride,
  isNullableAgentProvider,
  isNullableAgentRuntimeStatus,
  isNullableExecutionDirectoryMode,
  isNullableFiniteNumber,
  isNullableLaunchMode,
  isNullableString,
  isNullableTerminalRuntimeKind,
  isRecord,
  isRectOrNull,
  isSpaceBoundary,
  isStringArray,
  isTaskPriority,
  isTaskRuntimeStatus,
} from './persistedStateValidationPrimitives'

function isOptionalBoolean(value: unknown): boolean {
  return value === undefined || typeof value === 'boolean'
}

function isPullRequestSummary(value: unknown): boolean {
  if (!isRecord(value) || !isRecord(value.ref)) {
    return false
  }
  return (
    value.ref.providerId === 'github' &&
    value.ref.kind === 'pull_request' &&
    typeof value.ref.id === 'string' &&
    value.ref.id.trim().length > 0 &&
    isNullableString(value.ref.url) &&
    Number.isSafeInteger(value.number) &&
    (value.number as number) > 0 &&
    typeof value.title === 'string' &&
    (value.state === 'open' || value.state === 'closed' || value.state === 'merged') &&
    typeof value.isDraft === 'boolean' &&
    isNullableString(value.authorLogin) &&
    isNullableString(value.updatedAt) &&
    isNullableString(value.baseRefName) &&
    isNullableString(value.headRefName)
  )
}

function isArchiveGitSnapshot(value: unknown): value is PersistedSpaceArchiveGitSnapshot {
  return (
    isRecord(value) &&
    isNullableString(value.worktreePath) &&
    isNullableString(value.branch) &&
    isNullableString(value.head) &&
    (value.pullRequest === null || isPullRequestSummary(value.pullRequest))
  )
}

function hasArchiveNodeBase(value: Record<string, unknown>): boolean {
  return (
    typeof value.id === 'string' &&
    value.id.trim().length > 0 &&
    typeof value.title === 'string' &&
    isNodeFrameOrNull(value.frame) &&
    isNodeLabelColorOverride(value.labelColorOverride)
  )
}

function isArchiveNodeSnapshot(value: unknown): value is PersistedSpaceArchiveNodeSnapshot {
  if (!isRecord(value) || !hasArchiveNodeBase(value)) {
    return false
  }

  switch (value.kind) {
    case 'terminal':
      return (
        isNullableTerminalRuntimeKind(value.runtimeKind) &&
        isNullableString(value.executionDirectory) &&
        isNullableString(value.expectedDirectory) &&
        isNullableString(value.startedAt) &&
        isNullableString(value.endedAt) &&
        isNullableFiniteNumber(value.exitCode) &&
        isNullableString(value.lastError)
      )
    case 'agent':
      return (
        isNullableAgentRuntimeStatus(value.status) &&
        isNullableAgentProvider(value.provider) &&
        typeof value.prompt === 'string' &&
        isNullableString(value.model) &&
        isNullableString(value.effectiveModel) &&
        isNullableLaunchMode(value.launchMode) &&
        isNullableString(value.resumeSessionId) &&
        isOptionalBoolean(value.resumeSessionIdVerified) &&
        isNullableString(value.executionDirectory) &&
        isNullableString(value.expectedDirectory) &&
        isNullableExecutionDirectoryMode(value.directoryMode) &&
        isNullableString(value.customDirectory) &&
        typeof value.shouldCreateDirectory === 'boolean' &&
        isNullableString(value.taskId) &&
        isNullableString(value.startedAt) &&
        isNullableString(value.endedAt) &&
        isNullableFiniteNumber(value.exitCode) &&
        isNullableString(value.lastError)
      )
    case 'task':
      return (
        typeof value.requirement === 'string' &&
        isTaskRuntimeStatus(value.status) &&
        isTaskPriority(value.priority) &&
        isStringArray(value.tags) &&
        isNullableString(value.linkedAgentNodeId) &&
        isNullableString(value.lastRunAt) &&
        typeof value.autoGeneratedTitle === 'boolean' &&
        isNullableString(value.createdAt) &&
        isNullableString(value.updatedAt)
      )
    case 'note':
      return typeof value.text === 'string'
    default:
      return false
  }
}

function isArchiveSpaceSnapshot(value: unknown): value is PersistedSpaceArchiveSpaceSnapshot {
  return (
    isRecord(value) &&
    typeof value.id === 'string' &&
    value.id.trim().length > 0 &&
    typeof value.name === 'string' &&
    typeof value.directoryPath === 'string' &&
    isNullableString(value.targetMountId) &&
    isNullableString(value.parentSpaceId) &&
    (value.boundary === null || isSpaceBoundary(value.boundary)) &&
    (value.labelColor === null || isLabelColor(value.labelColor)) &&
    isStringArray(value.nodeIds) &&
    isRectOrNull(value.rect)
  )
}

export function isPersistedSpaceArchiveRecord(
  value: unknown,
): value is PersistedSpaceArchiveRecord {
  if (!isRecord(value) || !isRecord(value.space)) {
    return false
  }

  return (
    typeof value.id === 'string' &&
    value.id.trim().length > 0 &&
    typeof value.archivedAt === 'string' &&
    value.archivedAt.trim().length > 0 &&
    (value.git === null || isArchiveGitSnapshot(value.git)) &&
    typeof value.space.id === 'string' &&
    value.space.id.trim().length > 0 &&
    typeof value.space.name === 'string' &&
    typeof value.space.directoryPath === 'string' &&
    (value.space.labelColor === null || isLabelColor(value.space.labelColor)) &&
    isRectOrNull(value.space.rect) &&
    (value.spaces === undefined ||
      (Array.isArray(value.spaces) && value.spaces.every(isArchiveSpaceSnapshot))) &&
    Array.isArray(value.nodes) &&
    value.nodes.every(isArchiveNodeSnapshot)
  )
}
