import { chmod, mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { expect, test } from '@playwright/test'
import { clearAndSeedWorkspace, launchApp } from './workspace-canvas.helpers'
import { createNativeHookProvider } from './fixtures/create-native-hook-provider'

export function registerAgentHookRelayTests() {
  for (const provider of ['codex', 'claude-code'] as const) {
    const fileMode = provider === 'codex' && process.platform === 'win32'
    test(`${provider} executes ${fileMode ? 'session file observation' : 'Electron hooks'} through the real launch path and retains keyboard input`, async () => {
      const root = await mkdtemp(join(tmpdir(), 'OpenCove hook 路径 '))
      const fixture = resolve('tests/e2e/fixtures/agent-hook-provider.mjs')
      const quote = (value: string) => `'${value.replaceAll("'", `'"'"'`)}'`
      const executable =
        process.platform === 'win32'
          ? await createNativeHookProvider(root, fixture, provider)
          : join(root, 'provider')
      if (process.platform !== 'win32') {
        await writeFile(
          executable,
          `#!/bin/sh\nexec ${quote(process.execPath)} ${quote(fixture)} ${provider} "$@"\n`,
        )
      }
      await chmod(executable, 0o700)
      const { electronApp, window } = await launchApp({
        env: {
          CODEX_HOME: join(root, 'codex-home'),
          OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: fileMode ? '1' : '0',
          OPENCOVE_TEST_USE_REAL_AGENTS: '1',
          OPENCOVE_TEST_CLAUDE_HOOK_INSTALL_FAILURE: '0',
          OPENCOVE_TEST_CODEX_HOOK_INSTALL_FAILURE: '0',
        },
      })
      try {
        await clearAndSeedWorkspace(
          window,
          [
            {
              id: 'hook-task',
              title: 'Hook launch regression',
              position: { x: 180, y: 140 },
              width: 460,
              height: 280,
              kind: 'task',
              status: null,
              task: {
                requirement: 'Exercise Hook launch',
                status: 'todo',
                linkedAgentNodeId: null,
                lastRunAt: null,
                autoGeneratedTitle: false,
              },
            },
          ],
          {
            settings: {
              defaultProvider: provider,
              agentExecutablePathOverrideByProvider: { [provider]: executable },
              customModelEnabledByProvider: { [provider]: false },
            },
          },
        )
        await window.locator('[data-testid="task-node-run-agent"]').first().click()
        const node = window.locator('.terminal-node').first()
        await expect(node).toContainText('HOOK_PROVIDER_READY')
        const input = node.locator('.xterm-helper-textarea')
        await input.focus()
        await window.keyboard.press('Escape')
        await expect(node).toContainText('ESC_RECEIVED')
        // Each turn must complete before the next input to detect a stuck Hook.
        /* eslint-disable no-await-in-loop */
        for (const text of ['first', 'second', 'third']) {
          await window.keyboard.type(text)
          await window.keyboard.press('Enter')
          await expect(node).toContainText(`INPUT_OK=${text}`)
        }
        /* eslint-enable no-await-in-loop */
        await expect(node).toHaveAttribute(
          'data-agent-state-source',
          fileMode ? 'session_file' : provider === 'codex' ? 'codex_hook' : 'claude_hook',
        )
        await expect(node.locator('.terminal-node__status')).toHaveText('Standby')
        expect(
          await electronApp.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().length),
        ).toBe(1)
        await expect(node).not.toContainText('Hook failed')
      } finally {
        await electronApp.close()
        await rm(root, { recursive: true, force: true })
      }
    })
  }
}
