import { chmod, mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { expect, test } from '@playwright/test'
import { clearAndSeedWorkspace, launchApp } from './workspace-canvas.helpers'

export function registerAgentHookRelayTests() {
  for (const provider of ['codex', 'claude-code'] as const) {
    test(`${provider} executes Electron hooks through the real launch path and retains keyboard input`, async () => {
      // The Windows fixture is a .cmd shim, unlike the native provider executable. Keep its
      // own path literal for cmd /c trust discovery; production relay paths remain generated.
      const root = await mkdtemp(
        join(tmpdir(), process.platform === 'win32' ? 'opencove-hook-' : 'OpenCove hook 路径 '),
      )
      const executable = join(root, process.platform === 'win32' ? 'provider.cmd' : 'provider')
      const fixture = resolve('tests/e2e/fixtures/agent-hook-provider.mjs')
      const quote = (value: string) => `'${value.replaceAll("'", `'"'"'`)}'`
      await writeFile(
        executable,
        process.platform === 'win32'
          ? `@echo off\r\n"${process.execPath}" "${fixture}" ${provider} %*\r\n`
          : `#!/bin/sh\nexec ${quote(process.execPath)} ${quote(fixture)} ${provider} "$@"\n`,
      )
      await chmod(executable, 0o700)
      const { electronApp, window } = await launchApp({
        env: {
          OPENCOVE_TEST_USE_REAL_AGENTS: '1',
          OPENCOVE_TEST_CLAUDE_HOOK_INSTALL_FAILURE: '0',
          OPENCOVE_TEST_CODEX_HOOK_INSTALL_FAILURE: '0',
        },
      })
      try {
        await clearAndSeedWorkspace(
          window,
          [
            {
              id: 'hook-task',
              title: 'Hook launch regression',
              position: { x: 180, y: 140 },
              width: 460,
              height: 280,
              kind: 'task',
              status: null,
              task: {
                requirement: 'Exercise Hook launch',
                status: 'todo',
                linkedAgentNodeId: null,
                lastRunAt: null,
                autoGeneratedTitle: false,
              },
            },
          ],
          {
            settings: {
              defaultProvider: provider,
              agentExecutablePathOverrideByProvider: { [provider]: executable },
              customModelEnabledByProvider: { [provider]: false },
            },
          },
        )
        await window.locator('[data-testid="task-node-run-agent"]').first().click()
        const node = window.locator('.terminal-node').first()
        await expect(node).toContainText('HOOK_PROVIDER_READY')
        await expect(node).toHaveAttribute(
          'data-agent-state-source',
          provider === 'codex' ? 'codex_hook' : 'claude_hook',
        )
        const input = node.locator('.xterm-helper-textarea')
        await input.focus()
        await window.keyboard.press('Escape')
        await expect(node).toContainText('ESC_RECEIVED')
        // Each turn must complete before the next input to detect a stuck Hook.
        /* eslint-disable no-await-in-loop */
        for (const text of ['first', 'second', 'third']) {
          await window.keyboard.type(text)
          await window.keyboard.press('Enter')
          await expect(node).toContainText(`INPUT_OK=${text}`)
        }
        /* eslint-enable no-await-in-loop */
        await expect(node.locator('.terminal-node__status')).toHaveText('Standby')
        expect(
          await electronApp.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().length),
        ).toBe(1)
        await expect(node).not.toContainText('Hook failed')
      } finally {
        await electronApp.close()
        await rm(root, { recursive: true, force: true })
      }
    })
  }
}
