import { expect, test } from '@playwright/test'
import { clearAndSeedWorkspace, launchApp } from './workspace-canvas.helpers'

async function seedCodexTask(window: Awaited<ReturnType<typeof launchApp>>['window']) {
  await clearAndSeedWorkspace(
    window,
    [
      {
        id: 'task-agent-last-message',
        title: 'Capture agent answer',
        position: { x: 180, y: 140 },
        width: 460,
        height: 280,
        kind: 'task',
        status: null,
        task: {
          requirement: 'Wait for standby and copy the last agent message',
          status: 'todo',
          priority: 'medium',
          tags: ['notes'],
          linkedAgentNodeId: null,
          lastRunAt: null,
          autoGeneratedTitle: false,
          createdAt: '2026-03-15T00:00:00.000Z',
          updatedAt: '2026-03-15T00:00:00.000Z',
        },
      },
    ],
    {
      settings: {
        defaultProvider: 'codex',
        customModelEnabledByProvider: {
          'claude-code': false,
          codex: true,
        },
        customModelByProvider: {
          'claude-code': '',
          codex: 'gpt-5.2-codex',
        },
        customModelOptionsByProvider: {
          'claude-code': [],
          codex: ['gpt-5.2-codex'],
        },
      },
    },
  )
}

test.describe('Workspace Canvas - Agent Last Message Copy (Renderer Sandbox)', () => {
  test('copies the last standby agent message even when renderer sandbox is enabled', async () => {
    const { electronApp, window } = await launchApp({
      windowMode: 'offscreen',
      env: {
        OPENCOVE_E2E_FORCE_RENDERER_SANDBOX: '1',
        OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
        OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'codex-standby-no-newline',
      },
    })

    try {
      await seedCodexTask(window)
      await electronApp.evaluate(async ({ clipboard }) => {
        clipboard.clear()
      })

      const taskNode = window.locator('.task-node').first()
      await expect(taskNode).toBeVisible()
      await taskNode.locator('[data-testid="task-node-run-agent"]').click()

      const agentNode = window.locator('.terminal-node').first()
      const nodeStatus = agentNode.locator('.terminal-node__status')

      await expect(agentNode).toBeVisible()
      await expect(nodeStatus).toHaveText('Standby', { timeout: 15_000 })

      const copyButton = agentNode.locator('[data-testid="terminal-node-copy-last-message"]')
      await expect(copyButton).toBeVisible()
      await copyButton.evaluate(button => {
        button.click()
      })

      await expect
        .poll(async () => {
          return await electronApp.evaluate(async ({ clipboard }) => clipboard.readText())
        })
        .toBe('All set.')
    } finally {
      await electronApp.close()
    }
  })
})
