import { expect, test } from '@playwright/test'
import { clearAndSeedWorkspace, launchApp, testWorkspacePath } from './workspace-canvas.helpers'
import {
  clickPaneAtFlowPoint,
  ensureArtifactsDir,
  openPaneContextMenuAtFlowPoint,
  readSeededWorkspaceLayout,
} from './workspace-canvas.arrange.shared'

test.describe('Workspace Canvas - Arrange Semantics', () => {
  test('keeps note left and task-linked agent on the same row', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'note-lane',
          title: 'Idea',
          position: { x: 0, y: 0 },
          width: 320,
          height: 220,
          kind: 'note',
          task: {
            text: 'Keep the note in the idea lane.',
          },
        },
        {
          id: 'task-lane',
          title: 'Plan',
          position: { x: 0, y: 0 },
          width: 420,
          height: 300,
          kind: 'task',
          status: null,
          task: {
            requirement: 'Plan',
            status: 'todo',
            priority: 'medium',
            tags: [],
            linkedAgentNodeId: 'agent-lane',
            agentSessions: [],
            lastRunAt: null,
            autoGeneratedTitle: false,
            createdAt: '2026-02-09T00:00:00.000Z',
            updatedAt: '2026-02-09T00:00:00.000Z',
          },
        },
        {
          id: 'agent-lane',
          title: 'Execute',
          position: { x: 0, y: 0 },
          width: 560,
          height: 720,
          kind: 'agent',
          status: 'running',
          startedAt: '2026-02-09T00:05:00.000Z',
          endedAt: null,
          exitCode: null,
          lastError: null,
          agent: {
            provider: 'codex',
            prompt: 'Execute the planned task.',
            model: 'gpt-5.2-codex',
            effectiveModel: 'gpt-5.2-codex',
            launchMode: 'resume',
            resumeSessionId: '019c3e32-52ff-7b00-94ac-e6c5a56b4aa4',
            resumeSessionIdVerified: true,
            executionDirectory: testWorkspacePath,
            directoryMode: 'workspace',
            customDirectory: null,
            shouldCreateDirectory: false,
          },
        },
        {
          id: 'terminal-lane',
          title: 'Terminal',
          position: { x: 0, y: 0 },
          width: 470,
          height: 650,
          kind: 'terminal',
        },
      ])

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      await openPaneContextMenuAtFlowPoint(window, pane, { x: 900, y: 720 })
      await expect(window.locator('.workspace-context-menu')).toBeVisible()
      await window.locator('[data-testid="workspace-context-arrange-by"]').click()
      await expect(
        window.locator('[data-testid="workspace-context-arrange-by-menu"]'),
      ).toBeVisible()

      await window.locator('[data-testid="workspace-context-arrange-order-created"]').click()

      await expect
        .poll(async () => {
          return await readSeededWorkspaceLayout(window, {
            nodeIds: ['note-lane', 'task-lane', 'agent-lane', 'terminal-lane'],
            spaceIds: [],
          })
        })
        .toEqual({
          nodes: {
            'note-lane': { x: 0, y: 0, width: 228, height: 156 },
            'task-lane': { x: 240, y: 0, width: 228, height: 324 },
            'agent-lane': { x: 480, y: 0, width: 468, height: 660 },
            'terminal-lane': { x: 0, y: 672, width: 468, height: 324 },
          },
          spaces: {},
        })

      await ensureArtifactsDir()
      await clickPaneAtFlowPoint(window, pane, { x: 960, y: 760 })
      await expect(window.locator('.workspace-context-menu')).toHaveCount(0)
      await window.screenshot({
        path: 'artifacts/workspace-canvas-arrange.semantic-task-agent-pair.png',
      })
    } finally {
      await electronApp.close()
    }
  })
})
