import { expect, test, type Page } from '@playwright/test'
import {
  beginDragMouse,
  clearAndSeedWorkspace,
  launchApp,
  readLocatorClientRect,
} from './workspace-canvas.helpers'

async function readNodePosition(
  window: Page,
  nodeId: string,
): Promise<{ x: number; y: number } | null> {
  return await window.evaluate(async targetNodeId => {
    const raw = await window.opencoveApi.persistence.readWorkspaceStateRaw()
    if (!raw) {
      return null
    }

    const parsed = JSON.parse(raw) as {
      workspaces?: Array<{
        nodes?: Array<{
          id?: string
          position?: { x?: number; y?: number }
        }>
      }>
    }

    const nodes = parsed.workspaces?.[0]?.nodes ?? []
    const node = nodes.find(entry => entry.id === targetNodeId)
    if (
      !node?.position ||
      typeof node.position.x !== 'number' ||
      typeof node.position.y !== 'number'
    ) {
      return null
    }

    return {
      x: node.position.x,
      y: node.position.y,
    }
  }, nodeId)
}

test.describe('Workspace Canvas - Task Drag Renderer Recovery', () => {
  test('does not crash when task drag continues after a guarded transient renderer detach', async () => {
    const { electronApp, window } = await launchApp({ windowMode: 'inactive' })
    const pageErrors: string[] = []

    window.on('pageerror', error => {
      pageErrors.push(error.stack || error.message || String(error))
    })

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'drag-crash-task',
          title: 'Fix drag crash',
          position: { x: 220, y: 180 },
          width: 460,
          height: 280,
          kind: 'task',
          task: {
            requirement: 'Drag this task while a nearby terminal refreshes.',
            status: 'doing',
            priority: 'medium',
            tags: ['drag'],
            linkedAgentNodeId: null,
            lastRunAt: null,
            autoGeneratedTitle: false,
          },
        },
        {
          id: 'drag-crash-terminal',
          title: 'nearby-runtime',
          position: { x: 760, y: 180 },
          width: 520,
          height: 320,
          scrollback: '[opencove-test-agent] ready\\nline-2\\nline-3',
        },
      ])

      const taskNode = window.locator('.task-node').first()
      const terminalNode = window.locator('.terminal-node').first()
      const pane = window.locator('.workspace-canvas .react-flow__pane')

      await expect(taskNode).toBeVisible()
      await expect(terminalNode).toBeVisible()
      await expect(pane).toBeVisible()

      const before = await readNodePosition(window, 'drag-crash-task')
      if (!before) {
        throw new Error('task position unavailable before drag')
      }

      const sourceBox = await readLocatorClientRect(taskNode.locator('.task-node__header'))
      const targetBox = await readLocatorClientRect(pane)
      const drag = await beginDragMouse(window, {
        start: { x: sourceBox.x + 120, y: sourceBox.y + 18 },
        settleAfterPressMs: 0,
        settleBeforeReleaseMs: 0,
        settleAfterReleaseMs: 0,
      })
      try {
        const injected = await window.evaluate(() => {
          return window.__opencoveTerminalSelectionTestApi?.simulateDetachedRendererOnce?.(
            'drag-crash-terminal',
          )
        })
        expect(injected).toBe(true)
        expect(
          await window.evaluate(
            () =>
              window.__opencoveTerminalSelectionTestApi?.hasPendingDetachedRendererRead?.(
                'drag-crash-terminal',
              ) ?? null,
          ),
        ).toBe(true)

        await drag.moveTo({ x: targetBox.x + 260, y: targetBox.y + 220 })
      } finally {
        await drag.release()
      }

      await expect
        .poll(
          async () =>
            await window.evaluate(
              () =>
                window.__opencoveTerminalSelectionTestApi?.hasPendingDetachedRendererRead?.(
                  'drag-crash-terminal',
                ) ?? null,
            ),
        )
        .toBe(false)
      await expect(window.getByRole('heading', { name: '出现异常' })).toHaveCount(0)
      await expect(taskNode).toBeVisible()
      await expect(terminalNode).toBeVisible()

      await expect
        .poll(async () => {
          const after = await readNodePosition(window, 'drag-crash-task')
          if (!after) {
            return Number.NaN
          }

          return Math.hypot(after.x - before.x, after.y - before.y)
        })
        .toBeGreaterThan(60)

      expect(pageErrors).toEqual([])
    } finally {
      await electronApp.close()
    }
  })
})
