import { expect, test } from '@playwright/test'
import { clearAndSeedWorkspace, launchApp } from './workspace-canvas.helpers'
import {
  installPtySessionCapture,
  resolveFirstAgentSessionId,
  writeToPty,
} from './workspace-canvas.agent-status-watcher.helpers'

async function seedCodexTask(window: Awaited<ReturnType<typeof launchApp>>['window']) {
  await clearAndSeedWorkspace(
    window,
    [
      {
        id: 'task-codex-hook',
        title: 'Verify Codex hook status',
        position: { x: 180, y: 140 },
        width: 460,
        height: 280,
        kind: 'task',
        status: null,
        task: {
          requirement: 'Drive the managed Codex hook lifecycle',
          status: 'todo',
          priority: 'medium',
          tags: ['hook'],
          linkedAgentNodeId: null,
          lastRunAt: null,
          autoGeneratedTitle: false,
          createdAt: '2026-08-12T10:00:00.000Z',
          updatedAt: '2026-08-12T10:00:00.000Z',
        },
      },
    ],
    {
      settings: {
        defaultProvider: 'codex',
        customModelEnabledByProvider: { codex: false },
        customModelByProvider: { codex: '' },
        customModelOptionsByProvider: { codex: [] },
      },
    },
  )
}

async function launchCodexTask(window: Awaited<ReturnType<typeof launchApp>>['window']) {
  await seedCodexTask(window)
  await installPtySessionCapture(window)
  await window.locator('.task-node').first().locator('[data-testid="task-node-run-agent"]').click()
  const agentNode = window.locator('.terminal-node').first()
  await expect(agentNode).toBeVisible()
  await expect.poll(async () => await resolveFirstAgentSessionId(window)).not.toBeNull()
  const sessionId = await resolveFirstAgentSessionId(window)
  if (!sessionId) {
    throw new Error('Missing launched Codex PTY session id.')
  }
  return { sessionId, agentNode }
}

test.describe('Workspace Canvas - Codex hook channel', () => {
  test('projects authoritative waiting and standby from authenticated Codex hooks', async () => {
    const { electronApp, window } = await launchApp({
      windowMode: 'inactive',
      env: {
        OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
        OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'codex-hook-lifecycle',
        OPENCOVE_TEST_CODEX_HOOK_INSTALL_FAILURE: '0',
      },
    })
    try {
      const { sessionId, agentNode } = await launchCodexTask(window)
      const status = agentNode.locator('.terminal-node__status')

      await writeToPty(window, { sessionId, data: '<test-codex-hook-working>\r' })
      await expect(agentNode).toHaveAttribute('data-agent-state-source', 'codex_hook')
      await expect(status).toHaveText('Working')

      await writeToPty(window, { sessionId, data: '<test-codex-hook-waiting>\r' })
      await expect(status).toHaveText('Waiting')
      await expect(agentNode).toHaveAttribute('data-agent-state-source', 'codex_hook')

      await writeToPty(window, { sessionId, data: '<test-codex-hook-done>\r' })
      await expect(status).toHaveText('Standby')
      await expect(agentNode).toHaveAttribute('data-agent-state-source', 'codex_hook')
      await expect(agentNode).toHaveAttribute('data-agent-hook-install-state', 'installed')
    } finally {
      await electronApp.close()
    }
  })

  test('uses session-file state without a failure badge while the first installed hook is pending', async () => {
    const { electronApp, window } = await launchApp({
      windowMode: 'inactive',
      env: {
        OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
        OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'codex-hook-fallback',
        OPENCOVE_TEST_CODEX_HOOK_INSTALL_FAILURE: '0',
      },
    })
    try {
      const { agentNode } = await launchCodexTask(window)
      await expect(agentNode.locator('.terminal-node__status')).toHaveText('Standby')
      await expect(agentNode).toHaveAttribute('data-agent-state-source', 'session_file')
      await expect(agentNode).toHaveAttribute('data-agent-hook-install-state', 'installed')
      await expect(agentNode.locator('[data-testid="agent-hook-degraded"]')).toHaveCount(0)
      await window.screenshot({ path: test.info().outputPath('hook-pending.png') })
    } finally {
      await electronApp.close()
    }
  })
})
