import { expect, test } from '@playwright/test'
import {
  clearAndSeedWorkspace,
  launchApp,
  storageKey,
  testWorkspacePath,
} from './workspace-canvas.helpers'

test.describe('Workspace Canvas - Spaces (Auto Resize on Create)', () => {
  test('keeps the space unchanged and creates outside when no slot exists inside', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'space-crowded-left',
            title: 'crowded-left',
            position: { x: 240, y: 260 },
            width: 460,
            height: 280,
            kind: 'task',
            status: null,
            task: {
              requirement: 'left',
              status: 'todo',
              priority: 'low',
              tags: [],
              linkedAgentNodeId: null,
              agentSessions: [],
              lastRunAt: null,
              autoGeneratedTitle: false,
              createdAt: '2026-02-09T00:00:00.000Z',
              updatedAt: '2026-02-09T00:00:00.000Z',
            },
          },
          {
            id: 'space-crowded-right',
            title: 'crowded-right',
            position: { x: 720, y: 260 },
            width: 460,
            height: 280,
            kind: 'task',
            status: null,
            task: {
              requirement: 'right',
              status: 'todo',
              priority: 'low',
              tags: [],
              linkedAgentNodeId: null,
              agentSessions: [],
              lastRunAt: null,
              autoGeneratedTitle: false,
              createdAt: '2026-02-09T00:00:00.000Z',
              updatedAt: '2026-02-09T00:00:00.000Z',
            },
          },
          {
            id: 'root-near-space',
            title: 'root-near-space',
            position: { x: 1240, y: 260 },
            width: 460,
            height: 300,
            kind: 'terminal',
            status: null,
            startedAt: null,
            endedAt: null,
            exitCode: null,
            lastError: null,
            scrollback: null,
            executionDirectory: testWorkspacePath,
            expectedDirectory: testWorkspacePath,
            agent: null,
            task: null,
          },
        ],
        {
          spaces: [
            {
              id: 'space-crowded',
              name: 'Crowded Space',
              directoryPath: testWorkspacePath,
              nodeIds: ['space-crowded-left', 'space-crowded-right'],
              rect: { x: 200, y: 220, width: 1020, height: 420 },
            },
          ],
          activeSpaceId: null,
        },
      )

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      await pane.click({
        button: 'right',
        position: { x: 210, y: 280 },
      })
      await window.locator('[data-testid="workspace-context-new-task"]').click()

      await expect(window.locator('[data-testid="workspace-task-creator"]')).toBeVisible()
      await window.locator('[data-testid="workspace-task-advanced-toggle"]').click()
      await window.locator('[data-testid="workspace-task-title"]').fill('Crowded Task')
      await window.locator('[data-testid="workspace-task-requirement"]').fill('created-in-crowded')
      await window.locator('[data-testid="workspace-task-create-submit"]').click()

      await expect(window.locator('.task-node')).toHaveCount(3)

      await expect
        .poll(async () => {
          return await window.evaluate(
            async ({ key }) => {
              void key

              const raw = await window.opencoveApi.persistence.readWorkspaceStateRaw()
              if (!raw) {
                return null
              }

              const parsed = JSON.parse(raw) as {
                workspaces?: Array<{
                  nodes?: Array<{
                    id?: string
                    kind?: string
                    position?: { x?: number; y?: number }
                    width?: number
                    height?: number
                    task?: { requirement?: string } | null
                  }>
                  spaces?: Array<{
                    id?: string
                    rect?: { x?: number; y?: number; width?: number; height?: number } | null
                    nodeIds?: string[]
                  }>
                }>
              }

              const workspace = parsed.workspaces?.[0]
              if (!workspace) {
                return null
              }

              const space = (workspace.spaces ?? []).find(item => item.id === 'space-crowded')
              if (!space?.rect || !Array.isArray(space.nodeIds)) {
                return null
              }

              const rect = space.rect
              if (
                typeof rect.x !== 'number' ||
                typeof rect.y !== 'number' ||
                typeof rect.width !== 'number' ||
                typeof rect.height !== 'number'
              ) {
                return null
              }

              const originalRect = { x: 200, y: 220, width: 1020, height: 420 }
              const isSpaceRectUnchanged =
                rect.x === originalRect.x &&
                rect.y === originalRect.y &&
                rect.width === originalRect.width &&
                rect.height === originalRect.height

              const createdTask = (workspace.nodes ?? []).find(
                node => node.kind === 'task' && node.task?.requirement === 'created-in-crowded',
              )

              if (
                !createdTask?.position ||
                typeof createdTask.position.x !== 'number' ||
                typeof createdTask.position.y !== 'number' ||
                typeof createdTask.width !== 'number' ||
                typeof createdTask.height !== 'number'
              ) {
                return null
              }

              const createdTaskInSpace = space.nodeIds.includes(createdTask.id ?? '')
              const taskRight = createdTask.position.x + createdTask.width
              const taskBottom = createdTask.position.y + createdTask.height
              const spaceRight = rect.x + rect.width
              const spaceBottom = rect.y + rect.height
              const intersects = !(
                taskRight <= rect.x ||
                createdTask.position.x >= spaceRight ||
                taskBottom <= rect.y ||
                createdTask.position.y >= spaceBottom
              )

              return {
                isSpaceRectUnchanged,
                isSpaceMembershipUnchanged:
                  space.nodeIds.length === 2 &&
                  space.nodeIds.includes('space-crowded-left') &&
                  space.nodeIds.includes('space-crowded-right'),
                createdTaskInSpace,
                intersects,
              }
            },
            { key: storageKey },
          )
        })
        .toEqual({
          isSpaceRectUnchanged: true,
          isSpaceMembershipUnchanged: true,
          createdTaskInSpace: false,
          intersects: false,
        })
    } finally {
      await electronApp.close()
    }
  })
})
