import { chmod, mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { expect, test } from '@playwright/test'
import { clearAndSeedWorkspace, launchApp } from './workspace-canvas.helpers'
import { readRuntimeSessionId } from './workspace-canvas.terminal-agent-overlay.helpers'
import {
  resolveFirstAgentSessionId,
  writeToPty,
} from './workspace-canvas.agent-status-watcher.helpers'

// UI integration with a controlled Pi API fixture, not real-model acceptance.
test.describe('Pi native hook UI integration', () => {
  test.skip(
    process.platform === 'win32',
    'POSIX fixture launcher; Windows shim has separate contract coverage',
  )
  for (const entry of ['terminal', 'agent'] as const) {
    test(`${entry} launch follows native states, reload and explicit new-session binding`, async () => {
      const testInfo = test.info()
      const directory = await mkdtemp(path.join(tmpdir(), 'opencove-pi-ui-'))
      const executable = path.join(directory, 'pi')
      const fixture = path.resolve(__dirname, '../fixtures/agent/pi-lifecycle-stub.mjs')
      await writeFile(
        executable,
        `#!/bin/sh\nexec ${JSON.stringify(process.execPath)} ${JSON.stringify(fixture)} "$@"\n`,
      )
      await chmod(executable, 0o755)
      const { electronApp, window } = await launchApp({
        windowMode: 'offscreen',
        env: {
          PATH: `${directory}${path.delimiter}${process.env.PATH ?? ''}`,
          OPENCOVE_TEST_USE_REAL_AGENTS: '1',
          OPENCOVE_TEST_PI_SESSION_DIR: directory,
        },
      })
      try {
        await clearAndSeedWorkspace(
          window,
          [
            entry === 'terminal'
              ? {
                  id: 'pi-terminal',
                  kind: 'terminal',
                  title: 'Pi terminal',
                  position: { x: 180, y: 140 },
                  width: 520,
                  height: 400,
                }
              : {
                  id: 'pi-task',
                  kind: 'task',
                  title: 'Pi task',
                  position: { x: 180, y: 140 },
                  width: 460,
                  height: 280,
                  status: null,
                  task: {
                    requirement: 'Test Pi native observation',
                    status: 'todo',
                    linkedAgentNodeId: null,
                    lastRunAt: null,
                    autoGeneratedTitle: false,
                  },
                },
          ],
          {
            settings: {
              defaultProvider: 'pi',
              agentExecutablePathOverrideByProvider: { pi: executable },
              customModelEnabledByProvider: { pi: false },
              customModelByProvider: { pi: '' },
              customModelOptionsByProvider: { pi: [] },
            },
          },
        )
        if (entry === 'agent') {
          await window.getByTestId('task-node-run-agent').click()
        }
        const terminal = window.locator('.terminal-node').first()
        await expect(terminal).toBeVisible()
        if (entry === 'terminal') {
          await expect.poll(() => readRuntimeSessionId(window, 'pi-terminal')).toBeTruthy()
          await terminal.locator('.xterm-helper-textarea').click()
          await window.keyboard.type('pi')
          await window.keyboard.press('Enter')
        }
        await expect(terminal).toContainText('[pi-fixture] ready startup')
        const sessionId =
          entry === 'terminal'
            ? await readRuntimeSessionId(window, 'pi-terminal')
            : await resolveFirstAgentSessionId(window)
        expect(sessionId).toBeTruthy()
        const send = (data: string) =>
          writeToPty(window, { sessionId: sessionId!, data: `${data}\r` })
        const status = terminal.locator('.terminal-node__status')
        await send('/working')
        await expect(status).toHaveText('Working')
        await expect(terminal).toHaveAttribute('data-agent-state-source', 'pi_hook')
        await send('/wait')
        await expect(status).toHaveText('Waiting')
        await window.reload()
        await expect(status).toHaveText('Waiting')
        await expect(terminal).toHaveAttribute('data-agent-state-source', 'pi_hook')
        await send('/answer')
        await expect(status).toHaveText('Working')
        await send('/done')
        await expect(status).toHaveText('Standby')
        const binding = () =>
          window.evaluate(async kind => {
            const raw = await window.opencoveApi.persistence.readWorkspaceStateRaw()
            const state = raw ? JSON.parse(raw) : null
            const node = state?.workspaces
              ?.flatMap(workspace => workspace.nodes ?? [])
              .find(candidate => candidate.kind === kind && candidate.agent?.provider === 'pi')
            return node?.agent?.resumeSessionId ?? null
          }, entry)
        await expect.poll(binding).toMatch(/\.jsonl$/)
        const firstBinding = await binding()
        await send('/reload')
        await expect(terminal).toContainText('[pi-fixture] ready reload')
        await expect.poll(binding).toBe(firstBinding)
        await send('/new')
        await expect(terminal).toContainText('[pi-fixture] ready new')
        await expect.poll(binding).toBeNull()
        await send('/done')
        await expect.poll(binding).toMatch(/\.jsonl$/)
        expect(await binding()).not.toBe(firstBinding)
        await terminal.screenshot({ path: testInfo.outputPath(`pi-${entry}-standby.png`) })
        await send('/quit')
        if (entry === 'terminal') {
          await expect(status).toHaveCount(0)
        }
      } finally {
        await electronApp.close()
        await rm(directory, { recursive: true, force: true })
      }
    })
  }
})
