import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { expect, test } from '@playwright/test'
import {
  clearAndSeedWorkspace,
  createTestUserDataDir,
  launchApp,
  testWorkspacePath,
} from './workspace-canvas.helpers'
import {
  readObservedResumeSessionId,
  resolveFirstAgentSessionId,
} from './workspace-canvas.agent-status-watcher.helpers'

async function seedGeminiTask(
  window: Awaited<ReturnType<typeof launchApp>>['window'],
  resumeSessionId: string,
  startedAt: string,
) {
  await clearAndSeedWorkspace(
    window,
    [
      {
        id: 'task-agent-last-message',
        title: 'Copy gemini answer',
        position: { x: 180, y: 140 },
        width: 460,
        height: 280,
        kind: 'task',
        status: null,
        task: {
          requirement: 'Wait for standby and copy the last agent message',
          status: 'todo',
          priority: 'medium',
          tags: ['notes'],
          linkedAgentNodeId: 'agent-gemini-existing',
          lastRunAt: null,
          autoGeneratedTitle: false,
          createdAt: '2026-03-15T00:00:00.000Z',
          updatedAt: '2026-03-15T00:00:00.000Z',
        },
      },
      {
        id: 'agent-gemini-existing',
        title: 'gemini · existing session',
        position: { x: 680, y: 140 },
        width: 520,
        height: 320,
        kind: 'agent',
        status: 'standby',
        startedAt,
        agent: {
          provider: 'gemini',
          prompt: 'Resume the existing session',
          model: 'gemini-3-flash-preview',
          effectiveModel: 'gemini-3-flash-preview',
          launchMode: 'resume',
          resumeSessionId,
          resumeSessionIdVerified: true,
          executionDirectory: testWorkspacePath,
          expectedDirectory: testWorkspacePath,
          directoryMode: 'workspace',
          customDirectory: null,
          shouldCreateDirectory: false,
          taskId: 'task-agent-last-message',
        },
      },
    ],
    {
      settings: {
        defaultProvider: 'gemini',
        customModelEnabledByProvider: {
          'claude-code': false,
          codex: false,
          opencode: false,
          gemini: true,
        },
        customModelByProvider: {
          'claude-code': '',
          codex: '',
          opencode: '',
          gemini: 'gemini-3-flash-preview',
        },
        customModelOptionsByProvider: {
          'claude-code': [],
          codex: [],
          opencode: [],
          gemini: ['gemini-3-flash-preview'],
        },
      },
    },
  )
}

function normalizeGeminiProjectDirectoryName(cwd: string): string {
  const name = path.basename(cwd).trim()
  return name.length > 0 ? name.replace(/[^a-zA-Z0-9._-]/g, '-') : 'workspace'
}

function createGeminiTimestamp(timestampMs: number): string {
  return new Date(timestampMs).toISOString()
}

async function writeGeminiRoleSessionFile({
  userDataDir,
  cwd,
  sessionId,
  startedAtMs,
  messages,
}: {
  userDataDir: string
  cwd: string
  sessionId: string
  startedAtMs: number
  messages: Array<{
    role: 'user' | 'assistant'
    timestampMs: number
    content: unknown
  }>
}): Promise<void> {
  const projectDirectory = path.join(
    userDataDir,
    'home',
    '.gemini',
    'tmp',
    normalizeGeminiProjectDirectoryName(cwd),
  )
  const chatsDirectory = path.join(projectDirectory, 'chats')
  const sessionFilePath = path.join(chatsDirectory, `session-${sessionId}.json`)

  await mkdir(chatsDirectory, { recursive: true })
  await writeFile(path.join(projectDirectory, '.project_root'), cwd, 'utf8')

  await writeFile(
    sessionFilePath,
    JSON.stringify(
      {
        sessionId,
        projectHash: 'opencove-test-project-hash',
        startTime: createGeminiTimestamp(startedAtMs),
        lastUpdated: createGeminiTimestamp(messages.at(-1)?.timestampMs ?? startedAtMs),
        kind: 'main',
        // Some Gemini CLI versions emit `role` instead of `type`.
        messages: messages.map(message => ({
          id: `${message.role}-${message.timestampMs}`,
          timestamp: createGeminiTimestamp(message.timestampMs),
          role: message.role,
          content: message.content,
        })),
      },
      null,
      2,
    ),
    'utf8',
  )
}

test.describe('Workspace Canvas - Agent Last Message Copy (Gemini role session)', () => {
  test('copies the last assistant message from a role-based gemini session file', async () => {
    test.skip(
      process.platform === 'win32',
      'Windows offscreen Playwright input does not reliably submit the Gemini stub prompt.',
    )

    const userDataDir = await createTestUserDataDir()
    const { electronApp, window } = await launchApp({
      windowMode: 'offscreen',
      userDataDir,
      env: {
        OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
      },
    })

    try {
      const geminiSessionId = `gemini-role-e2e-${Date.now()}`
      const startedAtMs = Date.now()

      await writeGeminiRoleSessionFile({
        userDataDir,
        cwd: testWorkspacePath,
        sessionId: geminiSessionId,
        startedAtMs,
        messages: [
          {
            role: 'user',
            timestampMs: startedAtMs + 50,
            content: [{ text: 'Return OK only.' }],
          },
        ],
      })
      await seedGeminiTask(window, geminiSessionId, createGeminiTimestamp(startedAtMs))
      await electronApp.evaluate(async ({ clipboard }) => {
        clipboard.clear()
      })

      const taskNode = window.locator('.task-node').first()
      await expect(taskNode).toBeVisible()
      await expect(window.locator('.terminal-node')).toHaveCount(1)
      await expect(taskNode.locator('.agent-provider-icon')).toHaveAttribute(
        'data-agent-provider',
        'gemini',
      )

      let ptySessionId: string | null = null
      await expect
        .poll(async () => {
          ptySessionId = await resolveFirstAgentSessionId(window)
          return ptySessionId
        })
        .toBeTruthy()

      if (!ptySessionId) {
        throw new Error('Failed to resolve PTY session id')
      }

      await expect
        .poll(async () => await readObservedResumeSessionId(window, ptySessionId))
        .toBe(geminiSessionId)

      await writeGeminiRoleSessionFile({
        userDataDir,
        cwd: testWorkspacePath,
        sessionId: geminiSessionId,
        startedAtMs,
        messages: [
          {
            role: 'user',
            timestampMs: startedAtMs + 50,
            content: [{ text: 'Return OK only.' }],
          },
          {
            role: 'assistant',
            timestampMs: startedAtMs + 1_250,
            content: 'OK',
          },
        ],
      })

      const agentNode = window.locator('.terminal-node').first()
      const nodeStatus = agentNode.locator('.terminal-node__status')
      await expect(nodeStatus).toHaveText('Standby', { timeout: 15_000 })

      const copyButton = agentNode.locator('[data-testid="terminal-node-copy-last-message"]')
      await expect(copyButton).toBeVisible()
      await expect(copyButton).toBeEnabled()
      await copyButton.evaluate(button => {
        button.click()
      })

      await expect
        .poll(async () => {
          return await electronApp.evaluate(async ({ clipboard }) => clipboard.readText())
        })
        .toBe('OK')
    } finally {
      await electronApp.close()
    }
  })
})
