import { chmod, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { homedir, tmpdir } from 'node:os'
import path from 'node:path'
import { expect, test } from '@playwright/test'
import { clearAndSeedWorkspace, launchApp } from './workspace-canvas.helpers'
import { readRuntimeSessionId } from './workspace-canvas.terminal-agent-overlay.helpers'

// Opt-in: uses an installed Pi CLI and its existing authenticated model configuration.
// No credentials are copied. Prompts/transcripts are disposable; project resources and tools are disabled.
test.describe('Pi real-model acceptance', () => {
  test.skip(process.env.OPENCOVE_TEST_REAL_PI !== '1', 'Requires explicit real-model opt-in')
  test.skip(
    process.platform === 'win32',
    'POSIX wrapper; native Windows runtime remains unverified',
  )
  test.setTimeout(120_000)
  for (const entry of ['terminal', 'agent'] as const) {
    test(`${entry} launch reaches native settled state with a real model`, async () => {
      const directory = await mkdtemp(path.join(tmpdir(), 'opencove-pi-real-'))
      const executable = path.join(directory, 'pi')
      const realPi = process.env.OPENCOVE_REAL_PI_EXECUTABLE
      if (!realPi || !path.isAbsolute(realPi)) {
        throw new Error('Set OPENCOVE_REAL_PI_EXECUTABLE to the installed CLI absolute path')
      }
      await writeFile(
        executable,
        `#!/bin/sh\nexec ${JSON.stringify(realPi)} --offline --no-approve --no-extensions --no-context-files --no-skills --no-prompt-templates --no-builtin-tools --session-dir ${JSON.stringify(directory)} "$@"\n`,
      )
      await chmod(executable, 0o755)
      const { electronApp, window } = await launchApp({
        windowMode: 'offscreen',
        env: {
          PATH: `${directory}${path.delimiter}${process.env.PATH ?? ''}`,
          OPENCOVE_TEST_USE_REAL_AGENTS: '1',
          PI_CODING_AGENT_DIR:
            process.env.PI_CODING_AGENT_DIR ?? path.join(homedir(), '.pi', 'agent'),
        },
      })
      try {
        const prompt = 'Reply exactly OPENCOVE_PI_REAL_OK. Do not use tools.'
        await clearAndSeedWorkspace(
          window,
          [
            entry === 'terminal'
              ? {
                  id: 'pi-real-terminal',
                  kind: 'terminal',
                  title: 'Pi real terminal',
                  position: { x: 180, y: 140 },
                  width: 650,
                  height: 500,
                }
              : {
                  id: 'pi-real-task',
                  kind: 'task',
                  title: 'Pi real model',
                  position: { x: 180, y: 140 },
                  width: 460,
                  height: 280,
                  status: null,
                  task: {
                    requirement: prompt,
                    status: 'todo',
                    linkedAgentNodeId: null,
                    lastRunAt: null,
                    autoGeneratedTitle: false,
                  },
                },
          ],
          {
            settings: {
              defaultProvider: 'pi',
              agentExecutablePathOverrideByProvider: { pi: executable },
              customModelEnabledByProvider: { pi: false },
              customModelByProvider: { pi: '' },
              customModelOptionsByProvider: { pi: [] },
            },
          },
        )
        if (entry === 'agent') {
          await window.getByTestId('task-node-run-agent').click()
        }
        const terminal = window.locator('.terminal-node').first()
        await expect(terminal).toBeVisible()
        if (entry === 'terminal') {
          await expect.poll(() => readRuntimeSessionId(window, 'pi-real-terminal')).toBeTruthy()
          await terminal.locator('.xterm-helper-textarea').click()
          await window.keyboard.type('pi')
          await window.keyboard.press('Enter')
          await expect(terminal.locator('.terminal-node__status')).toHaveText('Standby')
          await expect(terminal).toHaveAttribute('data-agent-state-source', 'pi_hook')
          await expect(terminal).toContainText(/\d+(?:\.\d+)?%\/\d/)
          await window.keyboard.type(prompt)
          await window.keyboard.press('Enter')
        }
        await expect(terminal.locator('.terminal-node__status')).toHaveText('Working')
        await expect(terminal).toHaveAttribute('data-agent-state-source', 'pi_hook')
        await expect(terminal.locator('.terminal-node__status')).toHaveText('Standby', {
          timeout: 90_000,
        })
        await expect(terminal).toContainText('OPENCOVE_PI_REAL_OK')
        let sessionFile: string | null = null
        await expect
          .poll(async () => {
            sessionFile = await window.evaluate(async kind => {
              const raw = await window.opencoveApi.persistence.readWorkspaceStateRaw()
              const state = raw ? JSON.parse(raw) : null
              return (
                state?.workspaces
                  ?.flatMap(workspace => workspace.nodes ?? [])
                  .find(node => node.kind === kind && node.agent?.provider === 'pi')?.agent
                  ?.resumeSessionId ?? null
              )
            }, entry)
            return sessionFile
          })
          .toMatch(/\.jsonl$/)
        expect(path.dirname(sessionFile!)).toBe(directory)
        // The prompt itself contains the marker; require an actual persisted assistant response.
        const transcript = (await readFile(sessionFile!, 'utf8'))
          .trim()
          .split('\n')
          .map(line => JSON.parse(line))
        expect(
          transcript.some(
            record =>
              record.type === 'message' &&
              record.message?.role === 'assistant' &&
              record.message.content?.some(
                part => part.type === 'text' && part.text?.trim() === 'OPENCOVE_PI_REAL_OK',
              ),
          ),
        ).toBe(true)
        await terminal.screenshot({ path: test.info().outputPath(`pi-real-${entry}.png`) })
      } finally {
        await electronApp.close()
        await rm(directory, { recursive: true, force: true })
      }
    })
  }
})
