import { expect, test } from '@playwright/test'
import { clearAndSeedWorkspace, launchApp } from './workspace-canvas.helpers'
import {
  installPtySessionCapture,
  resolveFirstAgentSessionId,
  writeToPty,
} from './workspace-canvas.agent-status-watcher.helpers'

async function seedClaudeTask(window: Awaited<ReturnType<typeof launchApp>>['window']) {
  await clearAndSeedWorkspace(
    window,
    [
      {
        id: 'task-claude-hook',
        title: 'Verify hook status',
        position: { x: 180, y: 140 },
        width: 460,
        height: 280,
        kind: 'task',
        status: null,
        task: {
          requirement: 'Drive the managed hook lifecycle',
          status: 'todo',
          priority: 'medium',
          tags: ['hook'],
          linkedAgentNodeId: null,
          lastRunAt: null,
          autoGeneratedTitle: false,
          createdAt: '2026-08-12T10:00:00.000Z',
          updatedAt: '2026-08-12T10:00:00.000Z',
        },
      },
    ],
    {
      settings: {
        defaultProvider: 'claude-code',
        customModelEnabledByProvider: { 'claude-code': false },
        customModelByProvider: { 'claude-code': '' },
        customModelOptionsByProvider: { 'claude-code': [] },
      },
    },
  )
}

async function launchClaudeTask(
  window: Awaited<ReturnType<typeof launchApp>>['window'],
): Promise<{ sessionId: string; agentNode: ReturnType<typeof window.locator> }> {
  await seedClaudeTask(window)
  await installPtySessionCapture(window)
  const taskNode = window.locator('.task-node').first()
  await expect(taskNode).toBeVisible()
  await taskNode.locator('[data-testid="task-node-run-agent"]').click()
  const agentNode = window.locator('.terminal-node').first()
  await expect(agentNode).toBeVisible()
  await expect.poll(async () => await resolveFirstAgentSessionId(window)).not.toBeNull()
  const sessionId = await resolveFirstAgentSessionId(window)
  if (!sessionId) {
    throw new Error('Missing launched Claude PTY session id.')
  }
  return { sessionId, agentNode }
}

async function waitForInitialHookWorkingSignal(
  window: Awaited<ReturnType<typeof launchApp>>['window'],
  sessionId: string,
): Promise<void> {
  await writeToPty(window, { sessionId, data: '<test-hook-initial-working>\r' })
  // Drive the first hook POST only after the PTY session is observable. Until it lands,
  // session_file legitimately wins arbitration, so gate hook authority on the real signal.
  await expect
    .poll(async () => {
      return await window.evaluate(id => {
        return window.__opencoveAgentRunStateTestApi?.getSession(id)?.lastHookSignal?.state ?? null
      }, sessionId)
    })
    .toBe('working')
}

test.describe('Workspace Canvas - Claude hook channel', () => {
  test('projects authoritative working, waiting, and standby without tool-call false positives', async () => {
    const { electronApp, window } = await launchApp({
      windowMode: 'inactive',
      env: {
        OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
        OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'claude-hook-lifecycle',
        OPENCOVE_TEST_CLAUDE_HOOK_INSTALL_FAILURE: '0',
      },
    })
    try {
      const { sessionId, agentNode } = await launchClaudeTask(window)
      const status = agentNode.locator('.terminal-node__status')
      const sidebarStatus = window.locator('.workspace-agent-item__status--agent').first()

      await waitForInitialHookWorkingSignal(window, sessionId)
      await expect(agentNode).toHaveAttribute('data-agent-state-source', 'claude_hook')
      await expect(status).toHaveText('Working')
      await writeToPty(window, { sessionId, data: '<test-hook-tool>\r' })
      await expect(status).toHaveText('Working')
      await expect(agentNode).toHaveAttribute('data-agent-state-source', 'claude_hook')

      await writeToPty(window, { sessionId, data: '<test-hook-waiting>\r' })
      await expect(status).toHaveText('Waiting')
      await expect(sidebarStatus).toHaveText('Waiting')

      await writeToPty(window, { sessionId, data: '<test-hook-done>\r' })
      await expect(status).toHaveText('Standby')
      await expect(sidebarStatus).toHaveText('Standby')
      await expect(agentNode).toHaveAttribute('data-agent-hook-install-state', 'installed')
    } finally {
      await electronApp.close()
    }
  })

  test('launches with session-file fallback and visible degradation when hook install fails', async () => {
    const { electronApp, window } = await launchApp({
      windowMode: 'inactive',
      env: {
        OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
        OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'claude-hook-fallback',
        OPENCOVE_TEST_CLAUDE_HOOK_INSTALL_FAILURE: '1',
      },
    })
    try {
      const { sessionId, agentNode } = await launchClaudeTask(window)
      await expect(agentNode.locator('.terminal-node__status')).toHaveText('Standby')
      await expect(agentNode).toHaveAttribute('data-agent-state-source', 'session_file')
      await expect(agentNode).toHaveAttribute('data-agent-hook-install-state', 'error')
      await expect(agentNode.locator('[data-testid="agent-hook-degraded"]')).toHaveText('Fallback')

      await window.reload({ waitUntil: 'domcontentloaded' })

      const restoredAgentNode = window.locator('.terminal-node').first()
      await expect(restoredAgentNode).toBeVisible()
      await expect(restoredAgentNode.locator('.terminal-node__status')).toHaveText('Standby')
      await expect(restoredAgentNode).toHaveAttribute('data-agent-state-source', 'session_file')
      expect(await resolveFirstAgentSessionId(window)).toBe(sessionId)
    } finally {
      await electronApp.close()
    }
  })

  test('arbitrates conflicting sources and falls back exactly when working goes stale', async () => {
    const { electronApp, window } = await launchApp({
      windowMode: 'inactive',
      env: {
        OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
        OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'claude-hook-arbitration',
        OPENCOVE_TEST_CLAUDE_HOOK_INSTALL_FAILURE: '0',
      },
    })
    try {
      const { sessionId, agentNode } = await launchClaudeTask(window)
      const status = agentNode.locator('.terminal-node__status')

      await waitForInitialHookWorkingSignal(window, sessionId)
      await expect(agentNode).toHaveAttribute('data-agent-state-source', 'claude_hook')
      await expect(status).toHaveText('Working')
      await writeToPty(window, { sessionId, data: '<test-hook-waiting>\r' })
      await expect(status).toHaveText('Waiting')

      await writeToPty(window, { sessionId, data: '<test-session-standby>\r' })
      await expect
        .poll(async () => {
          return await window.evaluate(id => {
            return window.__opencoveAgentRunStateTestApi?.getSession(id)?.lastSessionFileSignal
              ?.state
          }, sessionId)
        })
        .toBe('standby')
      await expect(status).toHaveText('Waiting')
      await expect(agentNode).toHaveAttribute('data-agent-state-source', 'claude_hook')

      const agentNodeId = await agentNode.evaluate(
        element => element.closest('[data-id]')?.getAttribute('data-id') ?? null,
      )
      expect(agentNodeId).not.toBeNull()
      await window.reload({ waitUntil: 'domcontentloaded' })

      const restoredAgentNode = window.locator(`[data-id="${agentNodeId}"] .terminal-node`)
      await expect(restoredAgentNode).toBeVisible()
      await expect(restoredAgentNode.locator('.terminal-node__status')).toHaveText('Waiting')
      await expect(restoredAgentNode).toHaveAttribute('data-agent-state-source', 'claude_hook')
      expect(await resolveFirstAgentSessionId(window)).toBe(sessionId)

      expect(
        await window.evaluate(() => {
          return window.__opencoveAgentRunStateTestApi?.advanceBy(1_200_000) ?? false
        }),
      ).toBe(true)
      await expect(status).toHaveText('Waiting')
      await expect(agentNode).toHaveAttribute('data-agent-state-source', 'claude_hook')
      await window.evaluate(() => {
        window.__opencoveAgentRunStateTestApi?.resetClock()
      })

      await writeToPty(window, { sessionId, data: '<test-hook-done>\r' })
      await expect(status).toHaveText('Standby')
      await writeToPty(window, { sessionId, data: '<test-hook-tool>\r' })
      await expect(status).toHaveText('Working')

      expect(
        await window.evaluate(() => {
          return window.__opencoveAgentRunStateTestApi?.advanceBy(120_000) ?? false
        }),
      ).toBe(true)
      await expect(status).toHaveText('Standby')
      await expect(agentNode).toHaveAttribute('data-agent-state-source', 'session_file')
      await expect(agentNode.locator('[data-testid="agent-hook-degraded"]')).toHaveText('Fallback')
      await window.evaluate(() => {
        window.__opencoveAgentRunStateTestApi?.resetClock()
      })

      await writeToPty(window, { sessionId, data: '<test-hook-tool>\r' })
      await expect(status).toHaveText('Working')
      await expect(agentNode).toHaveAttribute('data-agent-state-source', 'claude_hook')
      await expect(agentNode.locator('[data-testid="agent-hook-degraded"]')).toHaveCount(0)
    } finally {
      await electronApp.close()
    }
  })
})
