import type {
  PersistedAgentRuntimeStatus,
  PersistedAppStateContract,
  PersistedExecutionDirectoryMode,
  PersistedNodeContract,
  PersistedNodeFrame,
  PersistedNodePayload,
  PersistedSpaceArchiveAgentSnapshot,
  PersistedSpaceArchiveNoteSnapshot,
  PersistedSpaceArchiveRecord,
  PersistedSpaceArchiveSpaceSnapshot,
  PersistedSpaceArchiveTaskSnapshot,
  PersistedSpaceArchiveTerminalSnapshot,
  PersistedSpaceContract,
  PersistedSpaceRect,
  PersistedTaskRuntimeStatus,
  PersistedViewport,
  PersistedWorkspaceContract,
} from './persistedAppState'
import type {
  AgentLaunchMode,
  AgentProviderId,
  GitHubPullRequestSummary,
  TaskPriority,
  TerminalRuntimeKind,
} from './dto'
import type { LabelColor, NodeLabelColorOverride } from '../types/labelColor'
import type { SpaceBoundary } from '../types/spaceBoundary'

export type NormalizedPersistedNodeContract = Omit<
  PersistedNodeContract,
  'agent' | 'endedAt' | 'exitCode' | 'lastError' | 'scrollback' | 'startedAt' | 'status' | 'task'
> & {
  status: PersistedAgentRuntimeStatus | null
  startedAt: string | null
  endedAt: string | null
  exitCode: number | null
  lastError: string | null
  scrollback: string | null
  agent: Exclude<PersistedNodeContract['agent'], undefined> | null
  task: PersistedNodePayload | null
}

export type NormalizedPersistedSpaceContract = Omit<
  PersistedSpaceContract,
  'directoryPath' | 'labelColor' | 'nodeIds' | 'rect' | 'targetMountId'
> & {
  directoryPath: string
  targetMountId: string | null
  labelColor: LabelColor | null
  nodeIds: string[]
  rect: PersistedSpaceRect | null
}

export type NormalizedPersistedSpaceArchiveSpaceSnapshot = Omit<
  PersistedSpaceArchiveSpaceSnapshot,
  | 'boundary'
  | 'directoryPath'
  | 'labelColor'
  | 'nodeIds'
  | 'parentSpaceId'
  | 'rect'
  | 'targetMountId'
> & {
  directoryPath: string
  targetMountId: string | null
  parentSpaceId: string | null
  boundary: SpaceBoundary | null
  labelColor: LabelColor | null
  nodeIds: string[]
  rect: PersistedSpaceRect | null
}

export interface NormalizedPersistedSpaceArchiveGitSnapshot {
  worktreePath: string | null
  branch: string | null
  head: string | null
  pullRequest: GitHubPullRequestSummary | null
}

type NormalizedArchiveNodeBase = {
  id: string
  title: string
  frame: PersistedNodeFrame | null
  labelColorOverride: NodeLabelColorOverride
}

export type NormalizedPersistedSpaceArchiveTerminalSnapshot = Omit<
  PersistedSpaceArchiveTerminalSnapshot,
  keyof NormalizedArchiveNodeBase | 'kind'
> &
  NormalizedArchiveNodeBase & {
    kind: 'terminal'
    runtimeKind: TerminalRuntimeKind | null
    executionDirectory: string | null
    expectedDirectory: string | null
    startedAt: string | null
    endedAt: string | null
    exitCode: number | null
    lastError: string | null
  }

export type NormalizedPersistedSpaceArchiveAgentSnapshot = Omit<
  PersistedSpaceArchiveAgentSnapshot,
  keyof NormalizedArchiveNodeBase | 'kind'
> &
  NormalizedArchiveNodeBase & {
    kind: 'agent'
    status: PersistedAgentRuntimeStatus | null
    provider: AgentProviderId | null
    prompt: string
    model: string | null
    effectiveModel: string | null
    launchMode: AgentLaunchMode | null
    resumeSessionId: string | null
    executionDirectory: string | null
    expectedDirectory: string | null
    directoryMode: PersistedExecutionDirectoryMode | null
    customDirectory: string | null
    shouldCreateDirectory: boolean
    taskId: string | null
    startedAt: string | null
    endedAt: string | null
    exitCode: number | null
    lastError: string | null
  }

export type NormalizedPersistedSpaceArchiveTaskSnapshot = Omit<
  PersistedSpaceArchiveTaskSnapshot,
  keyof NormalizedArchiveNodeBase | 'kind'
> &
  NormalizedArchiveNodeBase & {
    kind: 'task'
    status: PersistedTaskRuntimeStatus
    priority: TaskPriority
    tags: string[]
    linkedAgentNodeId: string | null
    lastRunAt: string | null
    autoGeneratedTitle: boolean
    createdAt: string | null
    updatedAt: string | null
  }

export type NormalizedPersistedSpaceArchiveNoteSnapshot = Omit<
  PersistedSpaceArchiveNoteSnapshot,
  keyof NormalizedArchiveNodeBase | 'kind'
> &
  NormalizedArchiveNodeBase & { kind: 'note' }

export type NormalizedPersistedSpaceArchiveNodeSnapshot =
  | NormalizedPersistedSpaceArchiveTerminalSnapshot
  | NormalizedPersistedSpaceArchiveAgentSnapshot
  | NormalizedPersistedSpaceArchiveTaskSnapshot
  | NormalizedPersistedSpaceArchiveNoteSnapshot

export type NormalizedPersistedSpaceArchiveRecord = Omit<
  PersistedSpaceArchiveRecord,
  'git' | 'nodes' | 'space' | 'spaces'
> & {
  git: NormalizedPersistedSpaceArchiveGitSnapshot | null
  space: {
    id: string
    name: string
    directoryPath: string
    labelColor: LabelColor | null
    rect: PersistedSpaceRect | null
  }
  spaces?: NormalizedPersistedSpaceArchiveSpaceSnapshot[]
  nodes: NormalizedPersistedSpaceArchiveNodeSnapshot[]
}

export type NormalizedPersistedWorkspaceContract = Omit<
  PersistedWorkspaceContract,
  | 'activeSpaceId'
  | 'isMinimapVisible'
  | 'nodes'
  | 'spaceArchiveRecords'
  | 'spaces'
  | 'viewport'
  | 'worktreesRoot'
> & {
  worktreesRoot: string
  nodes: NormalizedPersistedNodeContract[]
  viewport: PersistedViewport
  isMinimapVisible: boolean
  spaces: NormalizedPersistedSpaceContract[]
  activeSpaceId: string | null
  spaceArchiveRecords: NormalizedPersistedSpaceArchiveRecord[]
}

export type NormalizedPersistedAppStateContract<TSettings extends object> = Omit<
  PersistedAppStateContract<TSettings>,
  'workspaces'
> & {
  workspaces: NormalizedPersistedWorkspaceContract[]
}
