import type {
  AgentLaunchMode,
  AgentProviderId,
  BrowserMode,
  CanvasImageMimeType,
  TaskPriority,
  TerminalPtyGeometry,
  TerminalRuntimeKind,
  WebsiteWindowSessionMode,
} from '@shared/contracts/dto'
import type { LabelColor, NodeLabelColorOverride } from '@shared/types/labelColor'
import type { NodeWorkerBinding } from '@shared/types/nodeWorkerBinding'
import type { ProjectIconId } from '@shared/types/projectIcon'
import type { SpaceBoundary } from '@shared/types/spaceBoundary'

export const PERSISTED_WORKSPACE_NODE_KINDS = [
  'terminal',
  'agent',
  'task',
  'note',
  'role',
  'image',
  'document',
  'website',
] as const

export type PersistedWorkspaceNodeKind = (typeof PERSISTED_WORKSPACE_NODE_KINDS)[number]
export type PersistedAgentRuntimeStatus =
  | 'running'
  | 'standby'
  | 'waiting'
  | 'exited'
  | 'failed'
  | 'stopped'
  | 'restoring'
export type PersistedTaskRuntimeStatus = 'todo' | 'doing' | 'ai_done' | 'done'
export type PersistedExecutionDirectoryMode = 'workspace' | 'custom'

export type PersistedPoint = {
  x: number
  y: number
}

export type PersistedSize = {
  width: number
  height: number
}

export type PersistedNodeFrame = {
  position: PersistedPoint
  size: PersistedSize
}

export type PersistedViewport = PersistedPoint & {
  zoom: number
}

export type PersistedSpaceRect = PersistedPoint & PersistedSize

export interface PersistedTaskAgentSessionRecord {
  id: string
  provider: AgentProviderId
  resumeSessionId?: string | null
  resumeSessionIdVerified?: boolean
  prompt: string
  model?: string | null
  effectiveModel?: string | null
  boundDirectory: string
  lastDirectory?: string
  createdAt: string
  lastRunAt: string
  endedAt?: string | null
  exitCode?: number | null
  status?: PersistedAgentRuntimeStatus
}

export interface PersistedAgentNodeData {
  provider: AgentProviderId
  prompt?: string
  model?: string | null
  effectiveModel?: string | null
  launchMode?: AgentLaunchMode
  resumeSessionId?: string | null
  resumeSessionIdVerified?: boolean
  executionDirectory: string
  expectedDirectory?: string | null
  directoryMode?: PersistedExecutionDirectoryMode
  customDirectory?: string | null
  shouldCreateDirectory?: boolean
  taskId?: string | null
}

export interface PersistedTerminalAgentSessionBinding {
  provider: AgentProviderId
  resumeSessionId?: string | null
  resumeSessionIdVerified?: boolean
}

export interface PersistedTaskNodeData {
  requirement: string
  status?: PersistedTaskRuntimeStatus
  priority?: TaskPriority
  tags?: string[]
  linkedAgentNodeId?: string | null
  agentSessions?: PersistedTaskAgentSessionRecord[]
  lastRunAt?: string | null
  autoGeneratedTitle?: boolean
  createdAt?: string | null
  updatedAt?: string | null
}

export interface PersistedNoteNodeData {
  text?: string
}

export interface PersistedRoleRunRecord {
  id: string
  input?: string
  prompt?: string
  outputFormat?: string
  provider?: AgentProviderId | null
  agentNodeId?: string | null
  sessionId?: string | null
  createdAt: string
}

export interface PersistedRoleNodeData {
  roleId: string
  roleName: string
  roleDescription?: string
  promptTemplate?: string
  inputHint?: string
  outputFormat?: string
  input?: string
  selectedProvider?: AgentProviderId | null
  linkedAgentNodeId?: string | null
  runHistory?: PersistedRoleRunRecord[]
  createdAt?: string | null
  updatedAt?: string | null
}

export interface PersistedImageNodeData {
  assetId: string
  mimeType: CanvasImageMimeType
  fileName?: string | null
  naturalWidth?: number | null
  naturalHeight?: number | null
}

export interface PersistedDocumentNodeData {
  uri: string
}

export interface PersistedWebsiteNodeData {
  url?: string
  pinned?: boolean
  sessionMode?: WebsiteWindowSessionMode
  profileId?: string | null
  browserMode?: BrowserMode
  isFullscreen?: boolean
  previousFrame?: PersistedNodeFrame | null
}

export type PersistedNodePayload =
  | PersistedTaskNodeData
  | PersistedNoteNodeData
  | PersistedRoleNodeData
  | PersistedImageNodeData
  | PersistedDocumentNodeData
  | PersistedWebsiteNodeData

export interface PersistedNodeContract {
  id: string
  sessionId?: string | null
  title: string
  titlePinnedByUser?: boolean
  position: PersistedPoint
  width: number
  height: number
  kind: PersistedWorkspaceNodeKind
  profileId?: string | null
  runtimeKind?: TerminalRuntimeKind | null
  terminalGeometry?: TerminalPtyGeometry | null
  workerBinding?: NodeWorkerBinding | null
  terminalProviderHint?: AgentProviderId | null
  terminalAgentBinding?: PersistedTerminalAgentSessionBinding | null
  labelColorOverride?: NodeLabelColorOverride
  sidebarSortOrder?: number | null
  status?: PersistedAgentRuntimeStatus | null
  startedAt?: string | null
  endedAt?: string | null
  exitCode?: number | null
  lastError?: string | null
  scrollback?: string | null
  executionDirectory?: string | null
  expectedDirectory?: string | null
  agent?: PersistedAgentNodeData | PersistedTerminalAgentSessionBinding | null
  task?: PersistedNodePayload | null
}

export interface PersistedSpaceContract {
  id: string
  name: string
  directoryPath?: string
  targetMountId?: string | null
  parentSpaceId?: string | null
  boundary?: SpaceBoundary | null
  sortOrder?: number
  pinned?: boolean
  labelColor?: LabelColor | null
  nodeIds?: string[]
  rect?: PersistedSpaceRect | null
}

export interface PersistedSpaceArchiveSpaceSnapshot {
  id: string
  name: string
  directoryPath?: string
  targetMountId?: string | null
  parentSpaceId?: string | null
  boundary?: SpaceBoundary | null
  labelColor?: LabelColor | null
  nodeIds?: string[]
  rect?: PersistedSpaceRect | null
}

export interface PersistedSpaceArchiveRecord {
  id: string
  archivedAt: string
  git?: PersistedSpaceArchiveGitSnapshot | null
  space: {
    id: string
    name: string
    directoryPath?: string
    labelColor?: LabelColor | null
    rect?: PersistedSpaceRect | null
  }
  spaces?: PersistedSpaceArchiveSpaceSnapshot[]
  nodes?: PersistedSpaceArchiveNodeSnapshot[]
}

export interface PersistedGitHubPullRequestSummary {
  ref: {
    providerId: 'github'
    kind: 'pull_request'
    id: string
    url?: string | null
  }
  number: number
  title: string
  state: 'open' | 'closed' | 'merged'
  isDraft?: boolean
  authorLogin?: string | null
  updatedAt?: string | null
  baseRefName?: string | null
  headRefName?: string | null
}

export interface PersistedSpaceArchiveGitSnapshot {
  worktreePath?: string | null
  branch?: string | null
  head?: string | null
  pullRequest?: PersistedGitHubPullRequestSummary | null
}

interface PersistedSpaceArchiveNodeSnapshotBase {
  id: string
  title?: string
  frame?: PersistedNodeFrame | null
  labelColorOverride?: NodeLabelColorOverride
}

export interface PersistedSpaceArchiveTerminalSnapshot extends PersistedSpaceArchiveNodeSnapshotBase {
  kind: 'terminal'
  runtimeKind?: TerminalRuntimeKind | null
  executionDirectory?: string | null
  expectedDirectory?: string | null
  startedAt?: string | null
  endedAt?: string | null
  exitCode?: number | null
  lastError?: string | null
}

export interface PersistedSpaceArchiveAgentSnapshot extends PersistedSpaceArchiveNodeSnapshotBase {
  kind: 'agent'
  status?: PersistedAgentRuntimeStatus | null
  provider?: AgentProviderId | null
  prompt?: string
  model?: string | null
  effectiveModel?: string | null
  launchMode?: AgentLaunchMode | null
  resumeSessionId?: string | null
  resumeSessionIdVerified?: boolean
  executionDirectory?: string | null
  expectedDirectory?: string | null
  directoryMode?: PersistedExecutionDirectoryMode | null
  customDirectory?: string | null
  shouldCreateDirectory?: boolean
  taskId?: string | null
  startedAt?: string | null
  endedAt?: string | null
  exitCode?: number | null
  lastError?: string | null
}

export interface PersistedSpaceArchiveTaskSnapshot extends PersistedSpaceArchiveNodeSnapshotBase {
  kind: 'task'
  requirement: string
  status?: PersistedTaskRuntimeStatus
  priority?: TaskPriority
  tags?: string[]
  linkedAgentNodeId?: string | null
  lastRunAt?: string | null
  autoGeneratedTitle?: boolean
  createdAt?: string | null
  updatedAt?: string | null
}

export interface PersistedSpaceArchiveNoteSnapshot extends PersistedSpaceArchiveNodeSnapshotBase {
  kind: 'note'
  text: string
}

export type PersistedSpaceArchiveNodeSnapshot =
  | PersistedSpaceArchiveTerminalSnapshot
  | PersistedSpaceArchiveAgentSnapshot
  | PersistedSpaceArchiveTaskSnapshot
  | PersistedSpaceArchiveNoteSnapshot

export interface PersistedWorkspaceContract {
  id: string
  name: string
  iconId?: ProjectIconId | null
  path: string
  worktreesRoot?: string
  pullRequestBaseBranchOptions?: string[]
  environmentVariables?: Record<string, string>
  nodes: PersistedNodeContract[]
  viewport?: PersistedViewport
  isMinimapVisible?: boolean
  spaces?: PersistedSpaceContract[]
  activeSpaceId?: string | null
  spaceArchiveRecords?: PersistedSpaceArchiveRecord[]
}

/** Cross-process durable app-state shape specialized by the settings domain at each boundary. */
export interface PersistedAppStateContract<TSettings extends object> {
  formatVersion: number
  activeWorkspaceId: string | null
  workspaces: PersistedWorkspaceContract[]
  settings: TSettings
}
