import type { Node } from '@xyflow/react'
import { act, renderHook } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'
import type { TerminalNodeData } from '../../../src/contexts/workspace/presentation/renderer/types'
import {
  appendTaskAgentSessionRecordToHistory,
  createTaskAgentSessionRecord,
} from '../../../src/contexts/workspace/presentation/renderer/utils/agentSessionHistory'
import { useAgentNodeSessionSwitch } from '../../../src/contexts/workspace/presentation/renderer/components/workspaceCanvas/hooks/useAgentNodeSessionSwitch'

function createNodes(): Node<TerminalNodeData>[] {
  return [
    {
      id: 'task-1',
      position: { x: 0, y: 0 },
      data: {
        kind: 'task',
        sessionId: '',
        title: 'Task',
        width: 400,
        height: 300,
        status: null,
        startedAt: null,
        endedAt: null,
        exitCode: null,
        lastError: null,
        scrollback: null,
        agent: null,
        note: null,
        task: {
          requirement: 'Switch session',
          status: 'doing',
          priority: 'medium',
          tags: [],
          linkedAgentNodeId: 'agent-1',
          agentSessions: [],
          lastRunAt: null,
          autoGeneratedTitle: false,
          createdAt: null,
          updatedAt: null,
        },
      },
    },
    {
      id: 'agent-1',
      position: { x: 500, y: 0 },
      data: {
        kind: 'agent',
        sessionId: 'pty-current',
        title: 'Codex',
        width: 520,
        height: 380,
        status: 'standby',
        startedAt: '2026-09-04T00:00:00.000Z',
        endedAt: null,
        exitCode: null,
        lastError: null,
        scrollback: null,
        note: null,
        task: null,
        agent: {
          provider: 'codex',
          prompt: 'Current task',
          model: null,
          effectiveModel: null,
          launchMode: 'resume',
          resumeSessionId: 'resume-current',
          resumeSessionIdVerified: true,
          executionDirectory: '/workspace',
          expectedDirectory: '/workspace',
          directoryMode: 'workspace',
          customDirectory: null,
          shouldCreateDirectory: false,
          taskId: 'task-1',
        },
      },
    },
  ]
}

describe('agent session history', () => {
  it('does not expose task history to stale sync until the relaunch commits', async () => {
    const nodesRef = { current: createNodes() }
    let releaseRelaunch: (() => void) | null = null
    const relaunchAgentNode = vi.fn(async () => {
      await new Promise<void>(resolve => {
        releaseRelaunch = resolve
      })
      nodesRef.current = nodesRef.current.map(node =>
        node.id === 'agent-1' && node.data.agent
          ? {
              ...node,
              data: {
                ...node.data,
                agent: { ...node.data.agent, resumeSessionId: 'resume-target' },
              },
            }
          : node,
      )
    })
    const setNodes = vi.fn(updater => {
      nodesRef.current = updater(nodesRef.current)
    })
    const { result } = renderHook(() =>
      useAgentNodeSessionSwitch({ nodesRef, setNodes, relaunchAgentNode }),
    )

    let switchPromise: Promise<void> | null = null
    act(() => {
      switchPromise = result.current('agent-1', {
        provider: 'codex',
        sessionId: 'resume-target',
        cwd: '/workspace',
        startedAt: null,
        updatedAt: null,
        title: 'Target',
        source: 'codex-file',
      })
    })
    expect(nodesRef.current[0]?.data.task?.agentSessions).toEqual([])
    expect(setNodes).not.toHaveBeenCalled()

    releaseRelaunch?.()
    await act(async () => await switchPromise)

    expect(nodesRef.current[0]?.data.task?.agentSessions[0]).toMatchObject({
      resumeSessionId: 'resume-current',
    })
  })

  it('appends the captured previous binding after the live agent has switched sessions', () => {
    const before = createNodes()
    const record = createTaskAgentSessionRecord(before[1], '2026-09-04T01:00:00.000Z')
    expect(record).not.toBeNull()

    const current = createNodes().map(node =>
      node.id === 'agent-1' && node.data.agent
        ? {
            ...node,
            data: {
              ...node.data,
              agent: { ...node.data.agent, resumeSessionId: 'resume-target' },
            },
          }
        : node,
    )
    const next = appendTaskAgentSessionRecordToHistory({
      prevNodes: current,
      taskNodeId: 'task-1',
      agentSessionRecord: record!,
      now: '2026-09-04T01:00:00.000Z',
    })
    const task = next.find(node => node.id === 'task-1')?.data.task

    expect(task?.agentSessions).toHaveLength(1)
    expect(task?.agentSessions[0]).toMatchObject({
      resumeSessionId: 'resume-current',
      resumeSessionIdVerified: true,
    })
  })
})
