import React, { useState } from 'react'
import { fireEvent, render, screen } from '@testing-library/react'
import { describe, expect, it } from 'vitest'
import type {
  TaskCreatorState,
  TaskEditorState,
} from '../../../src/contexts/workspace/presentation/renderer/components/workspaceCanvas/types'
import { TaskCreatorWindow } from '../../../src/contexts/workspace/presentation/renderer/components/workspaceCanvas/windows/TaskCreatorWindow'
import { TaskEditorWindow } from '../../../src/contexts/workspace/presentation/renderer/components/workspaceCanvas/windows/TaskEditorWindow'

function TaskEditorHarness(): React.JSX.Element {
  const [taskEditor, setTaskEditor] = useState<TaskEditorState | null>({
    nodeId: 'task-edit-node',
    initialTitle: 'Initial Task Title',
    initialAutoGeneratedTitle: false,
    titleGeneratedInEditor: false,
    title: 'Initial Task Title',
    requirement: 'Initial requirement text',
    priority: 'medium',
    selectedTags: [],
    autoGenerateTitle: false,
    isGeneratingTitle: false,
    isSaving: false,
    error: null,
  })

  return (
    <TaskEditorWindow
      taskEditor={taskEditor}
      taskTitleProviderLabel="Codex"
      taskTitleModelLabel="gpt-5.2"
      taskTagOptions={[]}
      setTaskEditor={setTaskEditor}
      closeTaskEditor={() => {}}
      generateTaskEditorTitle={async () => {}}
      saveTaskEdits={async () => {}}
    />
  )
}

function TaskCreatorHarness(): React.JSX.Element {
  const [taskCreator, setTaskCreator] = useState<TaskCreatorState | null>({
    anchor: { x: 120, y: 80 },
    title: '',
    requirement: '',
    priority: 'medium',
    selectedTags: [],
    autoGenerateTitle: false,
    isGeneratingTitle: false,
    isCreating: false,
    error: null,
  })

  return (
    <TaskCreatorWindow
      taskCreator={taskCreator}
      taskTitleProviderLabel="Codex"
      taskTitleModelLabel="gpt-5.2"
      taskTagOptions={[]}
      setTaskCreator={setTaskCreator}
      closeTaskCreator={() => {}}
      generateTaskTitle={async () => {}}
      createTask={async () => {}}
    />
  )
}

describe('task priority select dialog layer', () => {
  it('raises the Task Editor priority menu above its modal backdrop', () => {
    render(<TaskEditorHarness />)

    fireEvent.click(screen.getByTestId('workspace-task-editor-priority-trigger'))

    const menu = screen.getByTestId('workspace-task-editor-priority-menu')
    expect(menu.parentElement).toBe(document.body)
    expect(menu).toHaveClass('cove-select__menu--within-dialog')
  })

  it('raises the Task Creator priority menu above its modal backdrop', () => {
    render(<TaskCreatorHarness />)

    fireEvent.click(screen.getByTestId('workspace-task-advanced-toggle'))
    fireEvent.click(screen.getByTestId('workspace-task-priority-trigger'))

    const menu = screen.getByTestId('workspace-task-priority-menu')
    expect(menu.parentElement).toBe(document.body)
    expect(menu).toHaveClass('cove-select__menu--within-dialog')
  })
})
