import { describe, expect, it } from 'vitest'
import type { Node } from '@xyflow/react'
import type {
  TerminalNodeData,
  WorkspaceSpaceState,
} from '../../../src/contexts/workspace/presentation/renderer/types'
import {
  arrangeWorkspaceCanvas,
  arrangeWorkspaceInSpace,
} from '../../../src/contexts/workspace/presentation/renderer/utils/workspaceArrange'

function createTerminalNode({
  id,
  position,
  size,
  kind = 'terminal',
  task = null,
}: {
  id: string
  position: { x: number; y: number }
  size: { width: number; height: number }
  kind?: TerminalNodeData['kind']
  task?: TerminalNodeData['task']
}): Node<TerminalNodeData> {
  return {
    id,
    type: 'terminalNode',
    position,
    data: {
      sessionId: `session-${id}`,
      title: id,
      width: size.width,
      height: size.height,
      kind,
      status: null,
      startedAt: null,
      endedAt: null,
      exitCode: null,
      lastError: null,
      scrollback: null,
      agent: null,
      task,
      note: null,
    } satisfies TerminalNodeData,
  }
}

function createTaskData({
  linkedAgentNodeId = null,
  createdAt = null,
}: {
  linkedAgentNodeId?: string | null
  createdAt?: string | null
} = {}): NonNullable<TerminalNodeData['task']> {
  return {
    requirement: 'Task',
    status: 'todo',
    priority: 'medium',
    tags: [],
    linkedAgentNodeId,
    agentSessions: [],
    lastRunAt: null,
    autoGeneratedTitle: false,
    createdAt,
    updatedAt: createdAt,
  }
}

describe('workspace arrange semantic grouping', () => {
  it('keeps linked task and agent together while notes stay on the left', () => {
    const nodes = [
      createTerminalNode({
        id: 'note',
        position: { x: 700, y: 400 },
        size: { width: 220, height: 140 },
        kind: 'note',
      }),
      createTerminalNode({
        id: 'task',
        position: { x: 900, y: 600 },
        size: { width: 220, height: 260 },
        kind: 'task',
        task: createTaskData({
          linkedAgentNodeId: 'agent',
          createdAt: '2026-02-09T00:00:00.000Z',
        }),
      }),
      createTerminalNode({
        id: 'agent',
        position: { x: 1200, y: 200 },
        size: { width: 400, height: 520 },
        kind: 'agent',
      }),
      createTerminalNode({
        id: 'terminal',
        position: { x: 300, y: 900 },
        size: { width: 400, height: 260 },
      }),
    ]

    const result = arrangeWorkspaceCanvas({
      nodes,
      spaces: [],
      wrapWidth: 1008,
      viewport: { width: 1440, height: 900 },
      style: { alignCanonicalSizes: true, order: 'createdAt' },
    })

    const nodeById = new Map(result.nodes.map(node => [node.id, node]))
    const note = nodeById.get('note')!
    const task = nodeById.get('task')!
    const agent = nodeById.get('agent')!
    const terminal = nodeById.get('terminal')!

    expect(note.position.y).toBe(task.position.y)
    expect(note.position.x).toBeLessThan(task.position.x)
    expect(task.position).toEqual({
      x: note.position.x + 240,
      y: note.position.y,
    })
    expect(agent.position).toEqual({
      x: task.position.x + 240,
      y: task.position.y,
    })
    expect(terminal.position).toEqual({
      x: note.position.x,
      y: note.position.y + 672,
    })
  })

  it('warns when keep-size space cannot fit a linked task-agent pair', () => {
    const nodes = [
      createTerminalNode({
        id: 'task',
        position: { x: 20, y: 20 },
        size: { width: 300, height: 220 },
        kind: 'task',
        task: createTaskData({ linkedAgentNodeId: 'agent' }),
      }),
      createTerminalNode({
        id: 'agent',
        position: { x: 360, y: 20 },
        size: { width: 500, height: 220 },
        kind: 'agent',
      }),
    ]

    const spaces: WorkspaceSpaceState[] = [
      {
        id: 'space-1',
        name: 'Space 1',
        directoryPath: '/tmp',
        nodeIds: ['task', 'agent'],
        rect: { x: 0, y: 0, width: 700, height: 400 },
      },
    ]

    const result = arrangeWorkspaceInSpace({
      spaceId: 'space-1',
      nodes,
      spaces,
      style: { alignCanonicalSizes: false, spaceFit: 'keep' },
    })

    expect(result.didChange).toBe(false)
    expect(result.nodes).toBe(nodes)
    expect(result.spaces).toBe(spaces)
    expect(result.warnings).toEqual([{ kind: 'space_no_room', spaceId: 'space-1' }])
  })
})
