import React, { useState } from 'react'
import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'
import type { Node } from '@xyflow/react'
import { DEFAULT_AGENT_SETTINGS } from '../../../src/contexts/settings/domain/agentSettings'
import type {
  TerminalNodeData,
  WorkspaceSpaceState,
  WorkspaceViewport,
} from '../../../src/contexts/workspace/presentation/renderer/types'
import { WorkspaceCanvas } from '../../../src/contexts/workspace/presentation/renderer/components/WorkspaceCanvas'
import { createMountAwareAgentControlSurface } from './workspaceCanvas.mountTestSupport'

vi.mock('@xyflow/react', () => {
  let currentNodes: Array<{ id: string; type: string; data: unknown }> = []

  return {
    ReactFlowProvider: ({ children }: { children: React.ReactNode }) => <>{children}</>,
    useReactFlow: () => ({
      screenToFlowPosition: ({ x, y }: { x: number; y: number }) => ({ x, y }),
      setCenter: vi.fn(),
      getViewport: vi.fn(() => ({ x: 0, y: 0, zoom: 1 })),
      setViewport: vi.fn(),
    }),
    useStore: (selector: (state: unknown) => unknown) => selector({ nodes: currentNodes }),
    useStoreApi: () => ({ setState: vi.fn(), getState: vi.fn(() => ({})), subscribe: vi.fn() }),
    ViewportPortal: ({ children }: { children: React.ReactNode }) => <>{children}</>,
    applyNodeChanges: (_changes: unknown, nodes: unknown) => nodes,
    ReactFlow: ({
      nodes,
      nodeTypes,
    }: {
      nodes: Array<{ id: string; type: string; data: unknown }>
      nodeTypes?: Record<string, React.ComponentType<{ id: string; data: unknown }>>
    }) => {
      currentNodes = nodes
      return (
        <div>
          {nodes.map(node => {
            const Renderer = nodeTypes?.[node.type]
            return Renderer ? <Renderer key={node.id} id={node.id} data={node.data} /> : null
          })}
        </div>
      )
    },
    Background: () => null,
    Controls: () => null,
    MiniMap: () => null,
    Handle: () => null,
    Position: { Left: 'left', Right: 'right' },
    BackgroundVariant: { Dots: 'dots' },
    SelectionMode: { Partial: 'partial' },
    MarkerType: { ArrowClosed: 'arrowclosed' },
    PanOnScrollMode: { Free: 'free' },
  }
})

vi.mock('../../../src/contexts/workspace/presentation/renderer/components/TerminalNode', () => {
  return {
    TerminalNode: ({ onBranchSession }: { onBranchSession?: () => Promise<void> }) => (
      <button type="button" data-testid="agent-branch" onClick={() => void onBranchSession?.()}>
        Branch
      </button>
    ),
  }
})

vi.mock('../../../src/contexts/workspace/presentation/renderer/components/TaskNode', () => {
  return { TaskNode: () => null }
})

function createInitialNodes(): Node<TerminalNodeData>[] {
  const now = '2026-04-29T00:00:00.000Z'

  return [
    {
      id: 'agent-1',
      type: 'terminalNode',
      position: { x: 0, y: 0 },
      data: {
        sessionId: 'session-current-pty',
        title: 'codex · model',
        width: 520,
        height: 400,
        kind: 'agent',
        status: 'standby',
        startedAt: now,
        endedAt: null,
        exitCode: null,
        lastError: null,
        scrollback: null,
        agent: {
          provider: 'codex',
          prompt: 'Do something important',
          model: 'gpt-5.2-codex',
          effectiveModel: 'gpt-5.2-codex',
          launchMode: 'resume',
          resumeSessionId: 'resume-current',
          resumeSessionIdVerified: true,
          executionDirectory: '/tmp/repo',
          expectedDirectory: '/tmp/repo',
          directoryMode: 'workspace',
          customDirectory: null,
          shouldCreateDirectory: false,
          taskId: 'task-1',
        },
        task: null,
        note: null,
        image: null,
        document: null,
        website: null,
      },
      draggable: true,
      selectable: true,
    },
    {
      id: 'task-1',
      type: 'taskNode',
      position: { x: 0, y: 520 },
      data: {
        sessionId: '',
        title: 'Task 1',
        width: 460,
        height: 280,
        kind: 'task',
        status: null,
        startedAt: null,
        endedAt: null,
        exitCode: null,
        lastError: null,
        scrollback: null,
        agent: null,
        task: {
          requirement: 'Improve retry logic',
          status: 'doing',
          priority: 'medium',
          tags: [],
          linkedAgentNodeId: 'agent-1',
          agentSessions: [],
          lastRunAt: now,
          autoGeneratedTitle: false,
          createdAt: now,
          updatedAt: now,
        },
        note: null,
        image: null,
        document: null,
        website: null,
      },
      draggable: true,
      selectable: true,
    },
  ]
}

function createInitialSpaces(): WorkspaceSpaceState[] {
  return [
    {
      id: 'space-1',
      name: 'Main',
      directoryPath: '/tmp/repo',
      targetMountId: 'mount-local',
      labelColor: null,
      nodeIds: ['agent-1', 'task-1'],
      rect: null,
    },
  ]
}

describe('WorkspaceCanvas agent branch mounted spaces', () => {
  it('relaunches a branch through the source space mount', async () => {
    const directLaunch = vi.fn(async () => ({ sessionId: 'session-direct' }))
    const launchInMount = vi.fn(async () => ({
      sessionId: 'session-branched-mounted',
      provider: 'codex' as const,
      command: 'codex',
      args: [],
      launchMode: 'resume' as const,
      effectiveModel: 'gpt-5.2-codex',
      resumeSessionId: 'resume-current',
      profileId: null,
      runtimeKind: 'posix' as const,
      startedAt: '2026-04-29T00:10:00.000Z',
      executionContext: {
        projectId: 'workspace-1',
        spaceId: null,
        mountId: 'mount-local',
        targetId: 'target-local',
        workingDirectory: '/tmp/repo',
        target: { rootPath: '/tmp/repo', rootUri: 'file:///tmp/repo' },
        scope: { rootPath: '/tmp/repo', rootUri: 'file:///tmp/repo' },
        endpoint: { endpointId: 'local', kind: 'local' as const },
      },
    }))
    const controlSurfaceInvoke = createMountAwareAgentControlSurface({
      workspaceId: 'workspace-1',
      rootPath: '/tmp/repo',
      launchInMount,
    })
    const requestPersistFlush = vi.fn()
    const randomUUID = vi.spyOn(crypto, 'randomUUID').mockReturnValueOnce('branch-agent-mounted')

    Object.defineProperty(window, 'opencoveApi', {
      configurable: true,
      writable: true,
      value: {
        pty: {
          kill: vi.fn(async () => undefined),
          onExit: vi.fn(() => () => undefined),
          spawn: vi.fn(async () => ({ sessionId: 'spawned' })),
        },
        workspace: { ensureDirectory: vi.fn(async () => undefined) },
        controlSurface: { invoke: controlSurfaceInvoke },
        agent: {
          launch: directLaunch,
          listSessions: vi.fn(async () => ({ provider: 'codex', cwd: '/tmp/repo', sessions: [] })),
        },
        task: {
          suggestTitle: vi.fn(async () => ({ title: 't', provider: 'codex', effectiveModel: null })),
        },
        meta: { isTest: true },
      },
    })

    const viewport: WorkspaceViewport = { x: 0, y: 0, zoom: 1 }
    let latestNodes = createInitialNodes()
    let latestSpaces: WorkspaceSpaceState[] = []

    function Harness() {
      const [nodes, setNodes] = useState(createInitialNodes())
      const [spaces, setSpaces] = useState<WorkspaceSpaceState[]>(createInitialSpaces())
      latestNodes = nodes
      latestSpaces = spaces

      return (
        <WorkspaceCanvas
          workspaceId="workspace-1"
          workspacePath="/tmp/repo"
          worktreesRoot=""
          nodes={nodes}
          onNodesChange={setNodes}
          onRequestPersistFlush={requestPersistFlush}
          spaces={spaces}
          activeSpaceId={null}
          onSpacesChange={setSpaces}
          onActiveSpaceChange={() => undefined}
          onAppendSpaceArchiveRecord={() => undefined}
          viewport={viewport}
          isMinimapVisible={false}
          onViewportChange={() => undefined}
          onMinimapVisibilityChange={() => undefined}
          agentSettings={DEFAULT_AGENT_SETTINGS}
        />
      )
    }

    render(<Harness />)
    fireEvent.click(screen.getByTestId('agent-branch'))

    await waitFor(() => {
      expect(launchInMount).toHaveBeenCalledTimes(1)
    })

    expect(directLaunch).not.toHaveBeenCalled()
    expect(controlSurfaceInvoke).toHaveBeenCalledWith({
      kind: 'query',
      id: 'mount.list',
      payload: { projectId: 'workspace-1' },
    })
    expect(launchInMount).toHaveBeenCalledWith(
      expect.objectContaining({
        mountId: 'mount-local',
        cwdUri: 'file:///tmp/repo',
        provider: 'codex',
        prompt: 'Do something important',
        mode: 'resume',
        model: 'gpt-5.2-codex',
        resumeSessionId: 'resume-current',
      }),
    )
    await waitFor(() => {
      const branchNode = latestNodes.find(node => node.id === 'branch-agent-mounted')
      expect(branchNode?.data.sessionId).toBe('session-branched-mounted')
      expect(latestSpaces[0].nodeIds).toEqual(['agent-1', 'task-1', 'branch-agent-mounted'])
    })

    randomUUID.mockRestore()
  })
})
