import type { Node } from '@xyflow/react'
import type { AgentRuntimeStatus } from '@contexts/agent/domain/types'
import type { AgentSettings, AgentProvider } from '@contexts/settings/domain/agentSettings'
import type { NodeLabelColorOverride } from '@shared/types/labelColor'
import type { ProjectIconId } from '@shared/types/projectIcon'
import type { NodeWorkerBinding } from '@shared/types/nodeWorkerBinding'
import type {
  PersistedAppStateContract,
  PersistedNodeContract,
  PersistedSpaceArchiveAgentSnapshot,
  PersistedSpaceArchiveGitSnapshot,
  PersistedSpaceArchiveNodeSnapshot,
  PersistedSpaceArchiveNoteSnapshot,
  PersistedSpaceArchiveRecord,
  PersistedSpaceArchiveSpaceSnapshot,
  PersistedSpaceArchiveTaskSnapshot,
  PersistedSpaceArchiveTerminalSnapshot,
  PersistedSpaceContract,
  PersistedSpaceRect,
  PersistedWorkspaceContract,
} from '@shared/contracts/persistedAppState'
import type {
  AgentHookInstallState,
  AgentRecoveryIssue,
  CanvasImageMimeType,
  TerminalPtyGeometry,
  TerminalAgentActivitySnapshot,
  TerminalRuntimeKind,
  TerminalSessionStateSource,
  WebsiteWindowSessionMode,
  BrowserMode,
} from '@shared/contracts/dto'

export type { AgentRuntimeStatus } from '@contexts/agent/domain/types'

export type WorkspaceNodeKind =
  | 'terminal'
  | 'agent'
  | 'task'
  | 'note'
  | 'role'
  | 'image'
  | 'document'
  | 'website'

export type TaskRuntimeStatus = 'todo' | 'doing' | 'ai_done' | 'done'

export type TaskPriority = 'low' | 'medium' | 'high' | 'urgent'

export type AgentLaunchMode = 'new' | 'resume'

export type ExecutionDirectoryMode = 'workspace' | 'custom'

export interface TaskAgentSessionRecord {
  id: string
  provider: AgentProvider
  resumeSessionId: string | null
  resumeSessionIdVerified?: boolean
  prompt: string
  model: string | null
  effectiveModel: string | null
  boundDirectory: string
  lastDirectory: string
  createdAt: string
  lastRunAt: string
  endedAt: string | null
  exitCode: number | null
  status: AgentRuntimeStatus
}

export interface AgentNodeData {
  provider: AgentProvider
  prompt: string
  model: string | null
  effectiveModel: string | null
  launchMode: AgentLaunchMode
  resumeSessionId: string | null
  resumeSessionIdVerified?: boolean
  executionDirectory: string
  expectedDirectory: string | null
  directoryMode: ExecutionDirectoryMode
  customDirectory: string | null
  shouldCreateDirectory: boolean
  taskId: string | null
}

export interface TerminalAgentSessionBinding {
  provider: AgentProvider
  resumeSessionId: string | null
  resumeSessionIdVerified?: boolean
}

export interface TerminalAgentOverlay {
  provider: AgentProvider
  status: AgentRuntimeStatus
  startedAtMs: number
  activity?:
    | (Pick<
        TerminalAgentActivitySnapshot,
        'invocationId' | 'generation' | 'phase' | 'observedAtMs' | 'sourceRevision' | 'revision'
      > & {
        verifiedProviderSessionId?: string | null
      })
    | null
}

export interface AgentRuntimeObservation {
  status: 'running' | 'waiting' | 'standby'
  source: TerminalSessionStateSource
  hookInstallState: AgentHookInstallState | null
  degraded: boolean
}

export interface TaskNodeData {
  requirement: string
  status: TaskRuntimeStatus
  priority: TaskPriority
  tags: string[]
  linkedAgentNodeId: string | null
  agentSessions: TaskAgentSessionRecord[]
  lastRunAt: string | null
  autoGeneratedTitle: boolean
  isEnriching?: boolean
  createdAt: string | null
  updatedAt: string | null
}

export interface NoteNodeData {
  text: string
}

export interface RoleRunRecord {
  id: string
  input: string
  prompt: string
  outputFormat: string
  provider: AgentProvider | null
  agentNodeId: string | null
  sessionId: string | null
  createdAt: string
}

export interface RoleNodeData {
  roleId: string
  roleName: string
  roleDescription: string
  promptTemplate: string
  inputHint: string
  outputFormat: string
  input: string
  selectedProvider: AgentProvider | null
  linkedAgentNodeId: string | null
  runHistory: RoleRunRecord[]
  createdAt: string | null
  updatedAt: string | null
}

export interface ImageNodeData {
  assetId: string
  mimeType: CanvasImageMimeType
  fileName: string | null
  naturalWidth: number | null
  naturalHeight: number | null
}

export interface DocumentNodeData {
  uri: string
}

export interface WebsiteNodeData {
  url: string
  pinned: boolean
  sessionMode: WebsiteWindowSessionMode
  profileId: string | null
  browserMode?: BrowserMode
  isFullscreen?: boolean
  previousFrame?: NodeFrame | null
}

export interface TerminalNodeData {
  [key: string]: unknown
  sessionId: string
  isLiveSessionReattach?: boolean
  autoFocus?: boolean
  profileId?: string | null
  runtimeKind?: TerminalRuntimeKind
  terminalGeometry?: TerminalPtyGeometry | null
  workerBinding?: NodeWorkerBinding | null
  terminalProviderHint?: AgentProvider | null
  terminalAgentBinding?: TerminalAgentSessionBinding | null
  agentOverlay?: TerminalAgentOverlay | null
  agentRuntimeObservation?: AgentRuntimeObservation | null
  labelColorOverride?: NodeLabelColorOverride
  sidebarSortOrder?: number
  title: string
  titlePinnedByUser?: boolean
  width: number
  height: number
  kind: WorkspaceNodeKind
  status: AgentRuntimeStatus | null
  startedAt: string | null
  endedAt: string | null
  exitCode: number | null
  lastError: string | null
  recoveryIssue?: AgentRecoveryIssue | null
  scrollback: string | null
  executionDirectory?: string | null
  expectedDirectory?: string | null
  agent: AgentNodeData | null
  task: TaskNodeData | null
  note: NoteNodeData | null
  role?: RoleNodeData | null
  image: ImageNodeData | null
  document: DocumentNodeData | null
  website: WebsiteNodeData | null
}

export interface WorkspaceState {
  id: string
  name: string
  iconId?: ProjectIconId | null
  path: string
  worktreesRoot: string
  pullRequestBaseBranchOptions?: string[]
  environmentVariables?: Record<string, string>
  nodes: Node<TerminalNodeData>[]
  viewport: WorkspaceViewport
  isMinimapVisible: boolean
  spaces: WorkspaceSpaceState[]
  activeSpaceId: string | null
  spaceArchiveRecords: SpaceArchiveRecord[]
}

export type PersistedTerminalNode = Omit<
  PersistedNodeContract,
  'agent' | 'runtimeKind' | 'sidebarSortOrder' | 'task'
> & {
  runtimeKind?: TerminalRuntimeKind
  sidebarSortOrder?: number
  agent: AgentNodeData | TerminalAgentSessionBinding | null
  task:
    | TaskNodeData
    | NoteNodeData
    | RoleNodeData
    | ImageNodeData
    | DocumentNodeData
    | WebsiteNodeData
    | null
}
export type PersistedWorkspaceState = Omit<PersistedWorkspaceContract, 'nodes'> & {
  nodes: PersistedTerminalNode[]
}
export type WorkspaceSpaceRect = PersistedSpaceRect
export type WorkspaceSpaceState = PersistedSpaceContract
export type SpaceArchiveSpaceSnapshot = PersistedSpaceArchiveSpaceSnapshot
export type SpaceArchiveRecord = PersistedSpaceArchiveRecord
export type SpaceArchiveGitSnapshot = PersistedSpaceArchiveGitSnapshot
export type SpaceArchiveNodeSnapshot = PersistedSpaceArchiveNodeSnapshot
export type SpaceArchiveTerminalSnapshot = PersistedSpaceArchiveTerminalSnapshot
export type SpaceArchiveAgentSnapshot = PersistedSpaceArchiveAgentSnapshot
export type SpaceArchiveTaskSnapshot = PersistedSpaceArchiveTaskSnapshot
export type SpaceArchiveNoteSnapshot = PersistedSpaceArchiveNoteSnapshot
export type PersistedAppState = Omit<PersistedAppStateContract<AgentSettings>, 'workspaces'> & {
  workspaces: PersistedWorkspaceState[]
}

export interface WorkspaceViewport {
  x: number
  y: number
  zoom: number
}

export const DEFAULT_WORKSPACE_VIEWPORT: WorkspaceViewport = {
  x: 0,
  y: 0,
  zoom: 1,
}

export const DEFAULT_WORKSPACE_MINIMAP_VISIBLE = true

export interface Size {
  width: number
  height: number
}

export interface Point {
  x: number
  y: number
}

export interface NodeFrame {
  position: Point
  size: Size
}
